In [1]:
# import libraries
import polars as pl
from datetime import date
from tqdm.notebook import tqdm
import plotly.express as px

pl.Config.set_tbl_rows(20)
pl.Config.set_tbl_cols(-1)
pl.Config.set_fmt_str_lengths(100)
pl.Config.set_tbl_width_chars(200)

# data path
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

from src.config import RAW_DIR, INTERIM_DIR, PROCESSED_DIR, DOCS_DIR

# 3. Data Preparation

## 3.1. Objective

Transform the raw dataset into a clean, consistent, leakage-controlled dataset suitable for downstream PD modeling.

The preparation follows the decisions established during Data Understanding:

* Analysis period starts January 2016.
* Only resolved loans are retained.
* Target is defined as Paid vs Default.
* Post-origination and target-related features are excluded.
* High-missingness features are removed.
* Variables are converted to appropriate analytical data types.

## 3.2. Load Data

In [2]:
# load data
lf = pl.scan_csv(
    RAW_DIR / "lending_club/Loan_status_2007-2020Q3.gzip",
    infer_schema_length=10000,
    ignore_errors=True)

In [3]:
lf.collect_schema()

Schema([('', Int64),
        ('id', Int64),
        ('loan_amnt', Int64),
        ('funded_amnt', Int64),
        ('funded_amnt_inv', Float64),
        ('term', String),
        ('int_rate', String),
        ('installment', Float64),
        ('grade', String),
        ('sub_grade', String),
        ('emp_title', String),
        ('emp_length', String),
        ('home_ownership', String),
        ('annual_inc', Float64),
        ('verification_status', String),
        ('issue_d', String),
        ('loan_status', String),
        ('pymnt_plan', String),
        ('url', String),
        ('purpose', String),
        ('title', String),
        ('zip_code', String),
        ('addr_state', String),
        ('dti', Float64),
        ('delinq_2yrs', Int64),
        ('earliest_cr_line', String),
        ('fico_range_low', Int64),
        ('fico_range_high', Int64),
        ('inq_last_6mths', Int64),
        ('mths_since_last_delinq', Int64),
        ('mths_since_last_record', Int64),
        ('open_acc', Int64),
        ('pub_rec', Int64),
        ('revol_bal', Int64),
        ('revol_util', String),
        ('total_acc', Int64),
        ('initial_list_status', String),
        ('out_prncp', Float64),
        ('out_prncp_inv', Float64),
        ('total_pymnt', Float64),
        ('total_pymnt_inv', Float64),
        ('total_rec_prncp', Float64),
        ('total_rec_int', Float64),
        ('total_rec_late_fee', Float64),
        ('recoveries', Float64),
        ('collection_recovery_fee', Float64),
        ('last_pymnt_d', String),
        ('last_pymnt_amnt', Float64),
        ('next_pymnt_d', String),
        ('last_credit_pull_d', String),
        ('last_fico_range_high', Int64),
        ('last_fico_range_low', Int64),
        ('collections_12_mths_ex_med', Int64),
        ('mths_since_last_major_derog', String),
        ('policy_code', Int64),
        ('application_type', String),
        ('annual_inc_joint', String),
        ('dti_joint', String),
        ('verification_status_joint', String),
        ('acc_now_delinq', Int64),
        ('tot_coll_amt', String),
        ('tot_cur_bal', String),
        ('open_acc_6m', String),
        ('open_act_il', String),
        ('open_il_12m', String),
        ('open_il_24m', String),
        ('mths_since_rcnt_il', String),
        ('total_bal_il', String),
        ('il_util', String),
        ('open_rv_12m', String),
        ('open_rv_24m', String),
        ('max_bal_bc', String),
        ('all_util', String),
        ('total_rev_hi_lim', String),
        ('inq_fi', String),
        ('total_cu_tl', String),
        ('inq_last_12m', String),
        ('acc_open_past_24mths', String),
        ('avg_cur_bal', String),
        ('bc_open_to_buy', String),
        ('bc_util', String),
        ('chargeoff_within_12_mths', Int64),
        ('delinq_amnt', Int64),
        ('mo_sin_old_il_acct', String),
        ('mo_sin_old_rev_tl_op', String),
        ('mo_sin_rcnt_rev_tl_op', String),
        ('mo_sin_rcnt_tl', String),
        ('mort_acc', String),
        ('mths_since_recent_bc', String),
        ('mths_since_recent_bc_dlq', String),
        ('mths_since_recent_inq', String),
        ('mths_since_recent_revol_delinq', String),
        ('num_accts_ever_120_pd', String),
        ('num_actv_bc_tl', String),
        ('num_actv_rev_tl', String),
        ('num_bc_sats', String),
        ('num_bc_tl', String),
        ('num_il_tl', String),
        ('num_op_rev_tl', String),
        ('num_rev_accts', String),
        ('num_rev_tl_bal_gt_0', String),
        ('num_sats', String),
        ('num_tl_120dpd_2m', String),
        ('num_tl_30dpd', String),
        ('num_tl_90g_dpd_24m', String),
        ('num_tl_op_past_12m', String),
        ('pct_tl_nvr_dlq', String),
        ('percent_bc_gt_75', String),
        ('pub_rec_bankruptcies', Int64),
        ('tax_liens', Int64),
        ('tot_hi_cred_lim', String),
        ('total_bal_ex_mort', String),
        ('total_bc_limit', String),
        ('total_il_high_credit_limit', String),
        ('revol_bal_joint', String),
        ('sec_app_fico_range_low', String),
        ('sec_app_fico_range_high', String),
        ('sec_app_earliest_cr_line', String),
        ('sec_app_inq_last_6mths', String),
        ('sec_app_mort_acc', String),
        ('sec_app_open_acc', String),
        ('sec_app_revol_util', String),
        ('sec_app_open_act_il', String),
        ('sec_app_num_rev_accts', String),
        ('sec_app_chargeoff_within_12_mths', String),
        ('sec_app_collections_12_mths_ex_med', String),
        ('hardship_flag', String),
        ('hardship_type', String),
        ('hardship_reason', String),
        ('hardship_status', String),
        ('deferral_term', String),
        ('hardship_amount', String),
        ('hardship_start_date', String),
        ('hardship_end_date', String),
        ('payment_plan_start_date', String),
        ('hardship_length', String),
        ('hardship_dpd', String),
        ('hardship_loan_status', String),
        ('orig_projected_additional_accrued_interest', String),
        ('hardship_payoff_balance_amount', String),
        ('hardship_last_payment_amount', String),
        ('debt_settlement_flag', String)])

In [4]:
lf.head(5).collect()

shape: (5, 142)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│     ┆ id  ┆ loa ┆ fun ┆ fun ┆ ter ┆ int ┆ ins ┆ gra ┆ sub ┆ emp ┆ emp ┆ hom ┆ ann ┆ ver ┆ iss ┆ loa ┆ pym ┆ url ┆ pur ┆ tit ┆ zip ┆ add ┆ dti ┆ del ┆ ear ┆ fic ┆ fic ┆ inq ┆ mth ┆ mth ┆ ope ┆ pub ┆ rev ┆ rev ┆ tot ┆ ini ┆ out ┆ out ┆ tot ┆ tot ┆ tot ┆ tot ┆ tot ┆ rec ┆ col ┆ las ┆ las ┆ nex ┆ las ┆ las ┆ las ┆ col ┆ mth ┆ pol ┆ app ┆ ann ┆ dti ┆ ver ┆ acc ┆ tot ┆ tot ┆ ope ┆ ope ┆ ope ┆ ope ┆ mth ┆ tot ┆ il_ ┆ ope ┆ ope ┆ max ┆ all ┆ tot ┆ inq ┆ tot ┆ inq ┆ acc ┆ avg ┆ bc_ ┆ bc_ ┆ cha ┆ del ┆ mo_ ┆ mo_ ┆ mo_ ┆ mo_ ┆ mor ┆ mth ┆ mth ┆ mth ┆ mth ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ pct ┆ per ┆ pub ┆ tax ┆ tot ┆ tot ┆ tot ┆ tot ┆ rev ┆ sec ┆ sec ┆ sec ┆ sec ┆ sec ┆ sec ┆ sec ┆ sec ┆ sec ┆ sec ┆ sec ┆ har ┆ har ┆ har ┆ har ┆ def ┆ har ┆ har ┆ har ┆ pay ┆ har ┆ har ┆ har ┆ ori ┆ har ┆ har ┆ deb │
│ --- ┆ --- ┆ n_a ┆ ded ┆ ded ┆ m   ┆ _ra ┆ tal ┆ de  ┆ _gr ┆ _ti ┆ _le ┆ e_o ┆ ual ┆ ifi ┆ ue_ ┆ n_s ┆ nt_ ┆ --- ┆ pos ┆ le  ┆ _co ┆ r_s ┆ --- ┆ inq ┆ lie ┆ o_r ┆ o_r ┆ _la ┆ s_s ┆ s_s ┆ n_a ┆ _re ┆ ol_ ┆ ol_ ┆ al_ ┆ tia ┆ _pr ┆ _pr ┆ al_ ┆ al_ ┆ al_ ┆ al_ ┆ al_ ┆ ove ┆ lec ┆ t_p ┆ t_p ┆ t_p ┆ t_c ┆ t_f ┆ t_f ┆ lec ┆ s_s ┆ icy ┆ lic ┆ ual ┆ _jo ┆ ifi ┆ _no ┆ _co ┆ _cu ┆ n_a ┆ n_a ┆ n_i ┆ n_i ┆ s_s ┆ al_ ┆ uti ┆ n_r ┆ n_r ┆ _ba ┆ _ut ┆ al_ ┆ _fi ┆ al_ ┆ _la ┆ _op ┆ _cu ┆ ope ┆ uti ┆ rge ┆ inq ┆ sin ┆ sin ┆ sin ┆ sin ┆ t_a ┆ s_s ┆ s_s ┆ s_s ┆ s_s ┆ _ac ┆ _ac ┆ _ac ┆ _bc ┆ _bc ┆ _il ┆ _op ┆ _re ┆ _re ┆ _sa ┆ _tl ┆ _tl ┆ _tl ┆ _tl ┆ _tl ┆ cen ┆ _re ┆ _li ┆ _hi ┆ al_ ┆ al_ ┆ al_ ┆ ol_ ┆ _ap ┆ _ap ┆ _ap ┆ _ap ┆ _ap ┆ _ap ┆ _ap ┆ _ap ┆ _ap ┆ _ap ┆ _ap ┆ dsh ┆ dsh ┆ dsh ┆ dsh ┆ err ┆ dsh ┆ dsh ┆ dsh ┆ men ┆ dsh ┆ dsh ┆ dsh ┆ g_p ┆ dsh ┆ dsh ┆ t_s │
│ i64 ┆ i64 ┆ mnt ┆ _am ┆ _am ┆ --- ┆ te  ┆ lme ┆ --- ┆ ade ┆ tle ┆ ngt ┆ wne ┆ _in ┆ cat ┆ d   ┆ tat ┆ pla ┆ str ┆ e   ┆ --- ┆ de  ┆ tat ┆ f64 ┆ _2y ┆ st_ ┆ ang ┆ ang ┆ st_ ┆ inc ┆ inc ┆ cc  ┆ c   ┆ bal ┆ uti ┆ acc ┆ l_l ┆ ncp ┆ ncp ┆ pym ┆ pym ┆ rec ┆ rec ┆ rec ┆ rie ┆ tio ┆ ymn ┆ ymn ┆ ymn ┆ red ┆ ico ┆ ico ┆ tio ┆ inc ┆ _co ┆ ati ┆ _in ┆ int ┆ cat ┆ w_d ┆ ll_ ┆ r_b ┆ cc_ ┆ ct_ ┆ l_1 ┆ l_2 ┆ inc ┆ bal ┆ l   ┆ v_1 ┆ v_2 ┆ l_b ┆ il  ┆ rev ┆ --- ┆ cu_ ┆ st_ ┆ en_ ┆ r_b ┆ n_t ┆ l   ┆ off ┆ _am ┆ _ol ┆ _ol ┆ _rc ┆ _rc ┆ cc  ┆ inc ┆ inc ┆ inc ┆ inc ┆ cts ┆ tv_ ┆ tv_ ┆ _sa ┆ _tl ┆ _tl ┆ _re ┆ v_a ┆ v_t ┆ ts  ┆ _12 ┆ _30 ┆ _90 ┆ _op ┆ _nv ┆ t_b ┆ c_b ┆ ens ┆ _cr ┆ bal ┆ bc_ ┆ il_ ┆ bal ┆ p_f ┆ p_f ┆ p_e ┆ p_i ┆ p_m ┆ p_o ┆ p_r ┆ p_o ┆ p_n ┆ p_c ┆ p_c ┆ ip_ ┆ ip_ ┆ ip_ ┆ ip_ ┆ al_ ┆ ip_ ┆ ip_ ┆ ip_ ┆ t_p ┆ ip_ ┆ ip_ ┆ ip_ ┆ roj ┆ ip_ ┆ ip_ ┆ ett │
│     ┆     ┆ --- ┆ nt  ┆ nt_ ┆ str ┆ --- ┆ nt  ┆ str ┆ --- ┆ --- ┆ h   ┆ rsh ┆ c   ┆ ion ┆ --- ┆ us  ┆ n   ┆     ┆ --- ┆ str ┆ --- ┆ e   ┆     ┆ rs  ┆ cr_ ┆ e_l ┆ e_h ┆ 6mt ┆ e_l ┆ e_l ┆ --- ┆ --- ┆ --- ┆ l   ┆ --- ┆ ist ┆ --- ┆ _in ┆ nt  ┆ nt_ ┆ _pr ┆ _in ┆ _la ┆ s   ┆ n_r ┆ t_d ┆ t_a ┆ t_d ┆ it_ ┆ _ra ┆ _ra ┆ ns_ ┆ e_l ┆ de  ┆ on_ ┆ c_j ┆ --- ┆ ion ┆ eli ┆ amt ┆ al  ┆ 6m  ┆ il  ┆ 2m  ┆ 4m  ┆ e_r ┆ _il ┆ --- ┆ 2m  ┆ 4m  ┆ c   ┆ --- ┆ _hi ┆ str ┆ tl  ┆ 12m ┆ pas ┆ al  ┆ o_b ┆ --- ┆ _wi ┆ nt  ┆ d_i ┆ d_r ┆ nt_ ┆ nt_ ┆ --- ┆ e_r ┆ e_r ┆ e_r ┆ e_r ┆ _ev ┆ bc_ ┆ rev ┆ ts  ┆ --- ┆ --- ┆ v_t ┆ cct ┆ l_b ┆ --- ┆ 0dp ┆ dpd ┆ g_d ┆ _pa ┆ r_d ┆ c_g ┆ ank ┆ --- ┆ ed_ ┆ _ex ┆ lim ┆ hig ┆ _jo ┆ ico ┆ ico ┆ arl ┆ nq_ ┆ ort ┆ pen ┆ evo ┆ pen ┆ um_ ┆ har ┆ oll ┆ fla ┆ typ ┆ rea ┆ sta ┆ ter ┆ amo ┆ sta ┆ end ┆ lan ┆ len ┆ dpd ┆ loa ┆ ect ┆ pay ┆ las ┆ lem │
│     ┆     ┆ i64 ┆ --- ┆ inv ┆     ┆ str ┆ --- ┆     ┆ str ┆ str ┆ --- ┆ ip  ┆ --- ┆ _st ┆ str ┆ --- ┆ --- ┆     ┆ str ┆     ┆ str ┆ --- ┆     ┆ --- ┆ lin ┆ ow  ┆ igh ┆ hs  ┆ ast ┆ ast ┆ i64 ┆ i64 ┆ i64 ┆ --- ┆ i64 ┆ _st ┆ f64 ┆ v   ┆ --- ┆ inv ┆ ncp ┆ t   ┆ te_ ┆ --- ┆ eco ┆ --- ┆ mnt ┆ --- ┆ pul ┆ nge ┆ nge ┆ 12_ ┆ ast ┆ --- ┆ typ ┆ oin ┆ str ┆ _st ┆ nq  ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ cnt ┆ --- ┆ str ┆ --- ┆ --- ┆ --- ┆ str ┆ _li ┆     ┆ --- ┆ --- ┆ t_2 ┆ --- ┆ uy  ┆ str ┆ thi ┆ --- ┆ l_a ┆ ev_ ┆ rev ┆ tl  ┆ str ┆ ece ┆ ece ┆ ece ┆ ece ┆ er_ ┆ tl  ┆ _tl ┆ --- ┆ str ┆ str ┆ l   ┆ s   ┆ al_ ┆ str ┆ d_2 ┆ --- ┆ pd_ ┆ st_ ┆ lq  ┆ t_7 ┆ rup ┆ i64 ┆ lim ┆ _mo ┆ it  ┆ h_c ┆ int ┆ _ra ┆ _ra ┆ ies ┆ las ┆ _ac ┆ _ac ┆ l_u ┆ _ac ┆ rev ┆ geo ┆ ect ┆ g   ┆ e   ┆ son ┆ tus ┆ m   ┆ unt ┆ rt_ ┆ _da ┆ _st ┆ gth ┆ --- ┆ n_s ┆ ed_ ┆ off ┆ t_p ┆ ent │
│     ┆     ┆     ┆ i64 ┆ --- ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆ str ┆ --- ┆ f64 ┆ atu ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆ i64 ┆ e   ┆ --- ┆ --- ┆ --- ┆ _de ┆ _re ┆     ┆     ┆     ┆ str ┆     ┆ atu ┆     ┆ --- ┆ f64 ┆ --- ┆ --- ┆ --- ┆ fee ┆ f64 ┆ ver ┆ str ┆ --- ┆ str ┆ l_d ┆ _hi ┆ _lo ┆ mth ┆ _ma ┆ i64 ┆ e   ┆ t   ┆     ┆ atu ┆ --- ┆ str ┆ str ┆ str ┆ str ┆ str ┆ str ┆ _il ┆ str ┆     ┆ str ┆ str ┆ str ┆     ┆ m   ┆     ┆ str ┆ str ┆ 4mt ┆ str ┆ --- ┆     ┆ n_1 ┆ i64 ┆ cct ┆ tl_ ┆ _tl ┆ --- ┆     ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ 120 ┆ --- ┆ --- ┆ str ┆     ┆     ┆ --- ┆ --- ┆ gt_ ┆     ┆ m   ┆ str ┆ 24m ┆ 12m ┆ --- ┆ 5   ┆ tci ┆     ┆ --- ┆ rt  ┆ --- ┆ red ┆ --- ┆ nge ┆ nge ┆ t_c ┆ t_6 ┆ c   ┆ c   ┆ til ┆ t_i ┆ _ac ┆ ff_ ┆ ion ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ dat ┆ te  ┆ art ┆ --- ┆ str ┆ tat ┆ add ┆ _ba ┆ aym ┆ _fl │
│     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ i64 ┆ i64 ┆ i64 ┆ lin ┆ cor ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆ f64 ┆     ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆     ┆ y_f ┆     ┆ f64 ┆     ┆ --- ┆ gh  ┆ w   ┆ s_e ┆ jor ┆     ┆ --- ┆ --- ┆     ┆ s_j ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ hs  ┆     ┆ str ┆     ┆ 2_m ┆     ┆ --- ┆ op  ┆ _op ┆ str ┆     ┆ bc  ┆ bc_ ┆ inq ┆ rev ┆ _pd ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆ str ┆ 0   ┆     ┆ --- ┆     ┆ --- ┆ --- ┆ str ┆ --- ┆ es  ┆     ┆ str ┆ --- ┆ str ┆ it_ ┆ str ┆ _lo ┆ _hi ┆ r_l ┆ mth ┆ --- ┆ --- ┆ --- ┆ l   ┆ cts ┆ wit ┆ s_1 ┆ str ┆ str ┆ str ┆ str ┆ str ┆ str ┆ e   ┆ --- ┆ _da ┆ str ┆     ┆ us  ┆ iti ┆ lan ┆ ent ┆ ag  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ q   ┆ d   ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ ee  ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ x_m ┆ _de ┆     ┆ str ┆ str ┆     ┆ oin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ ths ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ dlq ┆ --- ┆ ol_ ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆ --- ┆     ┆     ┆ str ┆     ┆ lim ┆     ┆ w   ┆ gh  ┆ ine ┆ s   ┆ str ┆ str ┆ str ┆ --- ┆ --- ┆ hin ┆ 2_m ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ te  ┆     ┆     ┆ --- ┆ ona ┆ ce_ ┆ _am ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆ ed  ┆ rog ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆ --- ┆ str ┆ del ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆ it  ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆ str ┆ str ┆ _12 ┆ ths ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆ str ┆ l_a ┆ amo ┆ oun ┆ str │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ inq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ str ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ _mt ┆ _ex ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ ccr ┆ unt ┆ t   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hs  ┆ _me ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ued ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _in ┆ str ┆ str ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ter ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ est ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0   ┆ 107 ┆ 500 ┆ 500 ┆ 497 ┆ 36  ┆ 10. ┆ 162 ┆ B   ┆ B2  ┆ nul ┆ 10+ ┆ REN ┆ 240 ┆ Ver ┆ Dec ┆ Ful ┆ n   ┆ htt ┆ cre ┆ Com ┆ 860 ┆ AZ  ┆ 27. ┆ 0   ┆ Jan ┆ 735 ┆ 739 ┆ 1   ┆ nul ┆ nul ┆ 3   ┆ 0   ┆ 136 ┆ 83. ┆ 9   ┆ f   ┆ 0.0 ┆ 0.0 ┆ 586 ┆ 583 ┆ 500 ┆ 863 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ Jan ┆ 171 ┆ nul ┆ May ┆ 704 ┆ 700 ┆ 0   ┆ nul ┆ 1   ┆ Ind ┆ nul ┆ nul ┆ nul ┆ 0   ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 0   ┆ 0   ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 0   ┆ 0   ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ N   ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ N   │
│     ┆ 750 ┆ 0   ┆ 0   ┆ 5.0 ┆ mon ┆ 65% ┆ .87 ┆     ┆     ┆ l   ┆ yea ┆ T   ┆ 00. ┆ ifi ┆ -20 ┆ ly  ┆     ┆ ps: ┆ dit ┆ put ┆ xx  ┆     ┆ 65  ┆     ┆ -19 ┆     ┆     ┆     ┆ l   ┆ l   ┆     ┆     ┆ 48  ┆ 7%  ┆     ┆     ┆     ┆     ┆ 3.1 ┆ 3.8 ┆ 0.0 ┆ .16 ┆     ┆     ┆     ┆ -20 ┆ .62 ┆ l   ┆ -20 ┆     ┆     ┆     ┆ l   ┆     ┆ ivi ┆ l   ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     │
│     ┆ 1   ┆     ┆     ┆     ┆ ths ┆     ┆     ┆     ┆     ┆     ┆ rs  ┆     ┆ 0   ┆ ed  ┆ 11  ┆ Pai ┆     ┆ //l ┆ _ca ┆ er  ┆     ┆     ┆     ┆     ┆ 85  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 551 ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆ 15  ┆     ┆     ┆ 20  ┆     ┆     ┆     ┆     ┆     ┆ dua ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆ end ┆ rd  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 87  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ing ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

## 3.3. Filter Data

In [5]:
# filter date
df = (lf
        .with_columns(pl.col("issue_d").str.strptime(pl.Date, "%b-%Y", strict=False).alias("issue_d"))  # cast date
        .filter(pl.col("issue_d") >= date(2016, 1, 1))                                                  # filter out data before 2016
    )

In [6]:
df.select(pl.len()).collect()

shape: (1, 1)
┌─────────┐
│ len     │
│ ---     │
│ u32     │
╞═════════╡
│ 2038052 │
└─────────┘

In [7]:
# filter loan status
LOAN_STATUS_MAP = {
    "Charged Off" : "default",
    "Default" : "default",
    "Does not meet the credit policy. Status:Charged Off" : "default",
    "Fully Paid" : "paid",
    "Does not meet the credit policy. Status:Fully Paid" : "paid",
    "Current": "not resolve",
    "In Grace Period": "not resolve",
    "Late (16-30 days)": "not resolve",
    "Late (31-120 days)": "not resolve",
    "Issued" : "not resolve"
}

df = (df
      .with_columns(
          pl.col("loan_status")
          .replace(LOAN_STATUS_MAP)                             # simplify loan status
          .alias("loan_status")
          .cast(pl.String))    
      .filter(pl.col("loan_status").is_in(["default", "paid"])) # filter resolved loan status
)

In [8]:
df.select(pl.len()).collect()

shape: (1, 1)
┌────────┐
│ len    │
│ ---    │
│ u32    │
╞════════╡
│ 994341 │
└────────┘

## 3.4. Drop Columns

In [9]:
# count column
lf.collect_schema().len()

142

In [10]:
# load data profile
data_profile = pl.read_parquet(INTERIM_DIR / "data_profile.parquet")

In [11]:
# filter pd eligible features
# list pd eligible features
col_pd_eligible = (data_profile
                    .filter(pl.col("pd_eligible") == True)   # keep only eligible rows
                    .select(pl.col("feature"))
                    .to_series()
                    .to_list())

col_pd_eligible = col_pd_eligible + ["loan_status", "issue_d"]  # add target column

# filter columns
df = df.select(col_pd_eligible)

In [12]:
df.collect_schema().len()

104

In [13]:
# drop null percentage > 90%
# list all columns
df_col = df.collect_schema().names()

# calculate null percentage
null_pct = (
    df
    .select([
        pl.col(col)
        .is_null()
        .mean()
        .mul(100)
        .round(2)
        .alias(col)
        for col in df_col
    ])
    .unpivot(
        variable_name="feature",
        value_name="missing_pct",
    )
    .sort("missing_pct", descending=True)
    .collect()
)

# list features with missing percentage > 90%
col_null = null_pct.filter(pl.col("missing_pct") > 90).select(pl.col("feature")).to_series().to_list()

# filter columns
df = df.select(pl.exclude(col_null))

In [14]:
df.collect_schema().len()

89

In [15]:
# filter post-origination features
# list post-origination features
col_post_origin = (data_profile
                    .filter(pl.col("availability") == "post_origination")   # keep only eligible rows
                    .select(pl.col("feature"))
                    .to_series()
                    .to_list())

# filter columns
df = df.select(pl.exclude(col_post_origin))

In [16]:
df.collect_schema().len()

89

## 3.5. Data Type Normalization

In [17]:
df.head(5).collect()

shape: (5, 89)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ loa ┆ fun ┆ fun ┆ ter ┆ int ┆ ins ┆ gra ┆ sub ┆ emp ┆ hom ┆ ann ┆ ver ┆ pur ┆ zip ┆ add ┆ dti ┆ del ┆ ear ┆ fic ┆ fic ┆ inq ┆ mth ┆ mth ┆ ope ┆ pub ┆ rev ┆ rev ┆ tot ┆ ini ┆ col ┆ mth ┆ app ┆ acc ┆ tot ┆ tot ┆ ope ┆ ope ┆ ope ┆ ope ┆ mth ┆ tot ┆ il_ ┆ ope ┆ ope ┆ max ┆ all ┆ tot ┆ inq ┆ tot ┆ inq ┆ acc ┆ avg ┆ bc_ ┆ bc_ ┆ cha ┆ del ┆ mo_ ┆ mo_ ┆ mo_ ┆ mo_ ┆ mor ┆ mth ┆ mth ┆ mth ┆ mth ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ pct ┆ per ┆ pub ┆ tax ┆ tot ┆ tot ┆ tot ┆ tot ┆ loa ┆ iss │
│ n_a ┆ ded ┆ ded ┆ m   ┆ _ra ┆ tal ┆ de  ┆ _gr ┆ _le ┆ e_o ┆ ual ┆ ifi ┆ pos ┆ _co ┆ r_s ┆ --- ┆ inq ┆ lie ┆ o_r ┆ o_r ┆ _la ┆ s_s ┆ s_s ┆ n_a ┆ _re ┆ ol_ ┆ ol_ ┆ al_ ┆ tia ┆ lec ┆ s_s ┆ lic ┆ _no ┆ _co ┆ _cu ┆ n_a ┆ n_a ┆ n_i ┆ n_i ┆ s_s ┆ al_ ┆ uti ┆ n_r ┆ n_r ┆ _ba ┆ _ut ┆ al_ ┆ _fi ┆ al_ ┆ _la ┆ _op ┆ _cu ┆ ope ┆ uti ┆ rge ┆ inq ┆ sin ┆ sin ┆ sin ┆ sin ┆ t_a ┆ s_s ┆ s_s ┆ s_s ┆ s_s ┆ _ac ┆ _ac ┆ _ac ┆ _bc ┆ _bc ┆ _il ┆ _op ┆ _re ┆ _re ┆ _sa ┆ _tl ┆ _tl ┆ _tl ┆ _tl ┆ _tl ┆ cen ┆ _re ┆ _li ┆ _hi ┆ al_ ┆ al_ ┆ al_ ┆ n_s ┆ ue_ │
│ mnt ┆ _am ┆ _am ┆ --- ┆ te  ┆ lme ┆ --- ┆ ade ┆ ngt ┆ wne ┆ _in ┆ cat ┆ e   ┆ de  ┆ tat ┆ f64 ┆ _2y ┆ st_ ┆ ang ┆ ang ┆ st_ ┆ inc ┆ inc ┆ cc  ┆ c   ┆ bal ┆ uti ┆ acc ┆ l_l ┆ tio ┆ inc ┆ ati ┆ w_d ┆ ll_ ┆ r_b ┆ cc_ ┆ ct_ ┆ l_1 ┆ l_2 ┆ inc ┆ bal ┆ l   ┆ v_1 ┆ v_2 ┆ l_b ┆ il  ┆ rev ┆ --- ┆ cu_ ┆ st_ ┆ en_ ┆ r_b ┆ n_t ┆ l   ┆ off ┆ _am ┆ _ol ┆ _ol ┆ _rc ┆ _rc ┆ cc  ┆ inc ┆ inc ┆ inc ┆ inc ┆ cts ┆ tv_ ┆ tv_ ┆ _sa ┆ _tl ┆ _tl ┆ _re ┆ v_a ┆ v_t ┆ ts  ┆ _12 ┆ _30 ┆ _90 ┆ _op ┆ _nv ┆ t_b ┆ c_b ┆ ens ┆ _cr ┆ bal ┆ bc_ ┆ il_ ┆ tat ┆ d   │
│ --- ┆ nt  ┆ nt_ ┆ str ┆ --- ┆ nt  ┆ str ┆ --- ┆ h   ┆ rsh ┆ c   ┆ ion ┆ --- ┆ --- ┆ e   ┆     ┆ rs  ┆ cr_ ┆ e_l ┆ e_h ┆ 6mt ┆ e_l ┆ e_l ┆ --- ┆ --- ┆ --- ┆ l   ┆ --- ┆ ist ┆ ns_ ┆ e_l ┆ on_ ┆ eli ┆ amt ┆ al  ┆ 6m  ┆ il  ┆ 2m  ┆ 4m  ┆ e_r ┆ _il ┆ --- ┆ 2m  ┆ 4m  ┆ c   ┆ --- ┆ _hi ┆ str ┆ tl  ┆ 12m ┆ pas ┆ al  ┆ o_b ┆ --- ┆ _wi ┆ nt  ┆ d_i ┆ d_r ┆ nt_ ┆ nt_ ┆ --- ┆ e_r ┆ e_r ┆ e_r ┆ e_r ┆ _ev ┆ bc_ ┆ rev ┆ ts  ┆ --- ┆ --- ┆ v_t ┆ cct ┆ l_b ┆ --- ┆ 0dp ┆ dpd ┆ g_d ┆ _pa ┆ r_d ┆ c_g ┆ ank ┆ --- ┆ ed_ ┆ _ex ┆ lim ┆ hig ┆ us  ┆ --- │
│ i64 ┆ --- ┆ inv ┆     ┆ str ┆ --- ┆     ┆ str ┆ --- ┆ ip  ┆ --- ┆ _st ┆ str ┆ str ┆ --- ┆     ┆ --- ┆ lin ┆ ow  ┆ igh ┆ hs  ┆ ast ┆ ast ┆ i64 ┆ i64 ┆ i64 ┆ --- ┆ i64 ┆ _st ┆ 12_ ┆ ast ┆ typ ┆ nq  ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ cnt ┆ --- ┆ str ┆ --- ┆ --- ┆ --- ┆ str ┆ _li ┆     ┆ --- ┆ --- ┆ t_2 ┆ --- ┆ uy  ┆ str ┆ thi ┆ --- ┆ l_a ┆ ev_ ┆ rev ┆ tl  ┆ str ┆ ece ┆ ece ┆ ece ┆ ece ┆ er_ ┆ tl  ┆ _tl ┆ --- ┆ str ┆ str ┆ l   ┆ s   ┆ al_ ┆ str ┆ d_2 ┆ --- ┆ pd_ ┆ st_ ┆ lq  ┆ t_7 ┆ rup ┆ i64 ┆ lim ┆ _mo ┆ it  ┆ h_c ┆ --- ┆ dat │
│     ┆ i64 ┆ --- ┆     ┆     ┆ f64 ┆     ┆     ┆ str ┆ --- ┆ f64 ┆ atu ┆     ┆     ┆ str ┆     ┆ i64 ┆ e   ┆ --- ┆ --- ┆ --- ┆ _de ┆ _re ┆     ┆     ┆     ┆ str ┆     ┆ atu ┆ mth ┆ _ma ┆ e   ┆ --- ┆ str ┆ str ┆ str ┆ str ┆ str ┆ str ┆ _il ┆ str ┆     ┆ str ┆ str ┆ str ┆     ┆ m   ┆     ┆ str ┆ str ┆ 4mt ┆ str ┆ --- ┆     ┆ n_1 ┆ i64 ┆ cct ┆ tl_ ┆ _tl ┆ --- ┆     ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ 120 ┆ --- ┆ --- ┆ str ┆     ┆     ┆ --- ┆ --- ┆ gt_ ┆     ┆ m   ┆ str ┆ 24m ┆ 12m ┆ --- ┆ 5   ┆ tci ┆     ┆ --- ┆ rt  ┆ --- ┆ red ┆ str ┆ e   │
│     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ i64 ┆ i64 ┆ i64 ┆ lin ┆ cor ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ s_e ┆ jor ┆ --- ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ hs  ┆     ┆ str ┆     ┆ 2_m ┆     ┆ --- ┆ op  ┆ _op ┆ str ┆     ┆ bc  ┆ bc_ ┆ inq ┆ rev ┆ _pd ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆ str ┆ 0   ┆     ┆ --- ┆     ┆ --- ┆ --- ┆ str ┆ --- ┆ es  ┆     ┆ str ┆ --- ┆ str ┆ it_ ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ q   ┆ d   ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ x_m ┆ _de ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ ths ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ dlq ┆ --- ┆ ol_ ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆ --- ┆     ┆     ┆ str ┆     ┆ lim ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆ ed  ┆ rog ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆ --- ┆ str ┆ del ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆ it  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ inq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 120 ┆ 120 ┆ 120 ┆ 36  ┆ 7.9 ┆ 375 ┆ A   ┆ A5  ┆ 10+ ┆ OWN ┆ 420 ┆ Sou ┆ deb ┆ 923 ┆ CA  ┆ 27. ┆ 0   ┆ Jun ┆ 715 ┆ 719 ┆ 0   ┆ nul ┆ 80  ┆ 9   ┆ 1   ┆ 114 ┆ 37% ┆ 16  ┆ w   ┆ 0   ┆ nul ┆ Ind ┆ 0   ┆ 0   ┆ 305 ┆ 1   ┆ 2   ┆ 1   ┆ 3   ┆ 8   ┆ 190 ┆ 73  ┆ 2   ┆ 4   ┆ 711 ┆ 53  ┆ 310 ┆ 1   ┆ 1   ┆ 2   ┆ 7   ┆ 338 ┆ 714 ┆ 53. ┆ 0   ┆ 0   ┆ 131 ┆ 255 ┆ 1   ┆ 1   ┆ 0   ┆ 14  ┆ nul ┆ 8   ┆ nul ┆ 0   ┆ 2   ┆ 6   ┆ 2   ┆ 2   ┆ 7   ┆ 7   ┆ 9   ┆ 6   ┆ 9   ┆ 0   ┆ 0   ┆ 0   ┆ 3   ┆ 100 ┆ 0   ┆ 1   ┆ 0   ┆ 571 ┆ 305 ┆ 155 ┆ 261 ┆ pai ┆ 201 │
│ 00  ┆ 00  ┆ 00. ┆ mon ┆ 7%  ┆ .88 ┆     ┆     ┆ yea ┆     ┆ 00. ┆ rce ┆ t_c ┆ xx  ┆     ┆ 74  ┆     ┆ -19 ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆ 57  ┆     ┆     ┆     ┆     ┆ l   ┆ ivi ┆     ┆     ┆ 02  ┆     ┆     ┆     ┆     ┆     ┆ 45  ┆     ┆     ┆     ┆ 7   ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆ 9   ┆ 4   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 80  ┆ 02  ┆ 00  ┆ 80  ┆ d   ┆ 7-0 │
│     ┆     ┆ 0   ┆ ths ┆     ┆     ┆     ┆     ┆ rs  ┆     ┆ 0   ┆ Ver ┆ ons ┆     ┆     ┆     ┆     ┆ 96  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dua ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ifi ┆ oli ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 100 ┆ 100 ┆ 100 ┆ 36  ┆ 9.4 ┆ 320 ┆ B   ┆ B1  ┆ 3   ┆ MOR ┆ 550 ┆ Not ┆ deb ┆ 971 ┆ OR  ┆ 18. ┆ 0   ┆ Sep ┆ 695 ┆ 699 ┆ 0   ┆ 68  ┆ 99  ┆ 7   ┆ 1   ┆ 718 ┆ 57. ┆ 10  ┆ w   ┆ 0   ┆ nul ┆ Ind ┆ 0   ┆ 0   ┆ 340 ┆ 0   ┆ 4   ┆ 1   ┆ 2   ┆ 10  ┆ 209 ┆ 75  ┆ 0   ┆ 0   ┆ 684 ┆ 68  ┆ 125 ┆ 1   ┆ 1   ┆ 1   ┆ 3   ┆ 486 ┆ 365 ┆ 65. ┆ 0   ┆ 0   ┆ 144 ┆ 73  ┆ 49  ┆ 10  ┆ 2   ┆ 49  ┆ nul ┆ 8   ┆ 68  ┆ 0   ┆ 1   ┆ 2   ┆ 1   ┆ 1   ┆ 5   ┆ 2   ┆ 3   ┆ 2   ┆ 7   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 100 ┆ 0   ┆ 1   ┆ 0   ┆ 315 ┆ 216 ┆ 105 ┆ 175 ┆ pai ┆ 201 │
│ 00  ┆ 00  ┆ 00. ┆ mon ┆ 4%  ┆ .05 ┆     ┆     ┆ yea ┆ TGA ┆ 00. ┆ Ver ┆ t_c ┆ xx  ┆     ┆ 79  ┆     ┆ -20 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆ 5%  ┆     ┆     ┆     ┆ l   ┆ ivi ┆     ┆     ┆ 607 ┆     ┆     ┆     ┆     ┆     ┆ 187 ┆     ┆     ┆     ┆ 7   ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆ 58  ┆ 3   ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 034 ┆ 375 ┆ 00  ┆ 048 ┆ d   ┆ 7-0 │
│     ┆     ┆ 0   ┆ ths ┆     ┆     ┆     ┆     ┆ rs  ┆ GE  ┆ 0   ┆ ifi ┆ ons ┆     ┆     ┆     ┆     ┆ 05  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dua ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ oli ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 800 ┆ 800 ┆ 800 ┆ 36  ┆ 16. ┆ 281 ┆ C   ┆ C5  ┆ < 1 ┆ MOR ┆ 120 ┆ Not ┆ deb ┆ 136 ┆ NY  ┆ 20. ┆ 0   ┆ Sep ┆ 700 ┆ 704 ┆ 1   ┆ 64  ┆ nul ┆ 8   ┆ 0   ┆ 190 ┆ 92. ┆ 34  ┆ w   ┆ 0   ┆ nul ┆ Joi ┆ 0   ┆ 0   ┆ 388 ┆ 2   ┆ 3   ┆ 2   ┆ 5   ┆ 6   ┆ 835 ┆ 85  ┆ 0   ┆ 0   ┆ 0   ┆ 88  ┆ 206 ┆ 1   ┆ 24  ┆ 2   ┆ 6   ┆ 555 ┆ nul ┆ nul ┆ 0   ┆ 0   ┆ 137 ┆ 276 ┆ 34  ┆ 6   ┆ 6   ┆ 152 ┆ nul ┆ 3   ┆ nul ┆ 0   ┆ 0   ┆ 3   ┆ 1   ┆ 2   ┆ 19  ┆ 4   ┆ 9   ┆ 3   ┆ 8   ┆ 0   ┆ 0   ┆ 0   ┆ 3   ┆ 97. ┆ nul ┆ 0   ┆ 0   ┆ 400 ┆ 102 ┆ 0   ┆ 899 ┆ pai ┆ 201 │
│ 0   ┆ 0   ┆ 0.0 ┆ mon ┆ 02% ┆ .34 ┆     ┆     ┆ yea ┆ TGA ┆ 000 ┆ Ver ┆ t_c ┆ xx  ┆     ┆ 36  ┆     ┆ -19 ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ 15  ┆ 3%  ┆     ┆     ┆     ┆ l   ┆ nt  ┆     ┆     ┆ 595 ┆     ┆     ┆     ┆     ┆     ┆ 72  ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆ 14  ┆ l   ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ l   ┆     ┆     ┆ 558 ┆ 587 ┆     ┆ 58  ┆ d   ┆ 7-0 │
│     ┆     ┆     ┆ ths ┆     ┆     ┆     ┆     ┆ r   ┆ GE  ┆ .0  ┆ ifi ┆ ons ┆     ┆     ┆     ┆     ┆ 94  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ App ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ oli ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 128 ┆ 128 ┆ 128 ┆ 36  ┆ 13. ┆ 434 ┆ C   ┆ C2  ┆ 5   ┆ REN ┆ 900 ┆ Not ┆ deb ┆ 799 ┆ TX  ┆ 22. ┆ 0   ┆ Dec ┆ 660 ┆ 664 ┆ 2   ┆ 43  ┆ nul ┆ 10  ┆ 0   ┆ 126 ┆ 86% ┆ 23  ┆ w   ┆ 0   ┆ 94  ┆ Ind ┆ 0   ┆ 0   ┆ 933 ┆ 2   ┆ 3   ┆ 2   ┆ 3   ┆ 6   ┆ 807 ┆ 91  ┆ 1   ┆ 3   ┆ 377 ┆ 86  ┆ 147 ┆ 0   ┆ 1   ┆ 2   ┆ 6   ┆ 103 ┆ 245 ┆ 86  ┆ 0   ┆ 0   ┆ 154 ┆ 345 ┆ 5   ┆ 5   ┆ 0   ┆ 5   ┆ nul ┆ 5   ┆ nul ┆ 0   ┆ 6   ┆ 6   ┆ 6   ┆ 6   ┆ 15  ┆ 6   ┆ 8   ┆ 6   ┆ 9   ┆ nul ┆ 0   ┆ 0   ┆ 3   ┆ 83  ┆ 83. ┆ 0   ┆ 0   ┆ 103 ┆ 933 ┆ 147 ┆ 882 ┆ pai ┆ 201 │
│ 00  ┆ 00  ┆ 00. ┆ mon ┆ 59% ┆ .93 ┆     ┆     ┆ yea ┆ T   ┆ 00. ┆ Ver ┆ t_c ┆ xx  ┆     ┆ 63  ┆     ┆ -19 ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ 60  ┆     ┆     ┆     ┆     ┆     ┆ ivi ┆     ┆     ┆ 75  ┆     ┆     ┆     ┆     ┆     ┆ 15  ┆     ┆     ┆     ┆ 7   ┆     ┆ 50  ┆     ┆     ┆     ┆     ┆ 75  ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆ 040 ┆ 75  ┆ 50  ┆ 90  ┆ d   ┆ 7-0 │
│     ┆     ┆ 0   ┆ ths ┆     ┆     ┆     ┆     ┆ rs  ┆     ┆ 0   ┆ ifi ┆ ons ┆     ┆     ┆     ┆     ┆ 88  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dua ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ oli ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [18]:
# cast data type
df = df.with_columns([

    # cast term to int
    pl.col("term")
      .str.strip_chars()
      .str.replace(" months", "")
      .cast(pl.Int8, strict=False),

    # cast int_rate
    pl.col("int_rate")
      .str.strip_chars()
      .str.replace("%", "")
      .cast(pl.Float64, strict=False),

    # cast revol_util
    pl.col("revol_util")
      .str.strip_chars()
      .str.replace("%", "")
      .cast(pl.Float64, strict=False),

    # cast emp_length
    pl.col("emp_length")
      .str.strip_chars()
      .str.replace(" years", "")
      .str.replace(" year", "")
      .str.replace("< 1", "0")
      .str.replace("10+", "10")
      .cast(pl.Int8, strict=False)
])

In [19]:
df.head(5).collect()

shape: (5, 89)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ loa ┆ fun ┆ fun ┆ ter ┆ int ┆ ins ┆ gra ┆ sub ┆ emp ┆ hom ┆ ann ┆ ver ┆ pur ┆ zip ┆ add ┆ dti ┆ del ┆ ear ┆ fic ┆ fic ┆ inq ┆ mth ┆ mth ┆ ope ┆ pub ┆ rev ┆ rev ┆ tot ┆ ini ┆ col ┆ mth ┆ app ┆ acc ┆ tot ┆ tot ┆ ope ┆ ope ┆ ope ┆ ope ┆ mth ┆ tot ┆ il_ ┆ ope ┆ ope ┆ max ┆ all ┆ tot ┆ inq ┆ tot ┆ inq ┆ acc ┆ avg ┆ bc_ ┆ bc_ ┆ cha ┆ del ┆ mo_ ┆ mo_ ┆ mo_ ┆ mo_ ┆ mor ┆ mth ┆ mth ┆ mth ┆ mth ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ pct ┆ per ┆ pub ┆ tax ┆ tot ┆ tot ┆ tot ┆ tot ┆ loa ┆ iss │
│ n_a ┆ ded ┆ ded ┆ m   ┆ _ra ┆ tal ┆ de  ┆ _gr ┆ _le ┆ e_o ┆ ual ┆ ifi ┆ pos ┆ _co ┆ r_s ┆ --- ┆ inq ┆ lie ┆ o_r ┆ o_r ┆ _la ┆ s_s ┆ s_s ┆ n_a ┆ _re ┆ ol_ ┆ ol_ ┆ al_ ┆ tia ┆ lec ┆ s_s ┆ lic ┆ _no ┆ _co ┆ _cu ┆ n_a ┆ n_a ┆ n_i ┆ n_i ┆ s_s ┆ al_ ┆ uti ┆ n_r ┆ n_r ┆ _ba ┆ _ut ┆ al_ ┆ _fi ┆ al_ ┆ _la ┆ _op ┆ _cu ┆ ope ┆ uti ┆ rge ┆ inq ┆ sin ┆ sin ┆ sin ┆ sin ┆ t_a ┆ s_s ┆ s_s ┆ s_s ┆ s_s ┆ _ac ┆ _ac ┆ _ac ┆ _bc ┆ _bc ┆ _il ┆ _op ┆ _re ┆ _re ┆ _sa ┆ _tl ┆ _tl ┆ _tl ┆ _tl ┆ _tl ┆ cen ┆ _re ┆ _li ┆ _hi ┆ al_ ┆ al_ ┆ al_ ┆ n_s ┆ ue_ │
│ mnt ┆ _am ┆ _am ┆ --- ┆ te  ┆ lme ┆ --- ┆ ade ┆ ngt ┆ wne ┆ _in ┆ cat ┆ e   ┆ de  ┆ tat ┆ f64 ┆ _2y ┆ st_ ┆ ang ┆ ang ┆ st_ ┆ inc ┆ inc ┆ cc  ┆ c   ┆ bal ┆ uti ┆ acc ┆ l_l ┆ tio ┆ inc ┆ ati ┆ w_d ┆ ll_ ┆ r_b ┆ cc_ ┆ ct_ ┆ l_1 ┆ l_2 ┆ inc ┆ bal ┆ l   ┆ v_1 ┆ v_2 ┆ l_b ┆ il  ┆ rev ┆ --- ┆ cu_ ┆ st_ ┆ en_ ┆ r_b ┆ n_t ┆ l   ┆ off ┆ _am ┆ _ol ┆ _ol ┆ _rc ┆ _rc ┆ cc  ┆ inc ┆ inc ┆ inc ┆ inc ┆ cts ┆ tv_ ┆ tv_ ┆ _sa ┆ _tl ┆ _tl ┆ _re ┆ v_a ┆ v_t ┆ ts  ┆ _12 ┆ _30 ┆ _90 ┆ _op ┆ _nv ┆ t_b ┆ c_b ┆ ens ┆ _cr ┆ bal ┆ bc_ ┆ il_ ┆ tat ┆ d   │
│ --- ┆ nt  ┆ nt_ ┆ i8  ┆ --- ┆ nt  ┆ str ┆ --- ┆ h   ┆ rsh ┆ c   ┆ ion ┆ --- ┆ --- ┆ e   ┆     ┆ rs  ┆ cr_ ┆ e_l ┆ e_h ┆ 6mt ┆ e_l ┆ e_l ┆ --- ┆ --- ┆ --- ┆ l   ┆ --- ┆ ist ┆ ns_ ┆ e_l ┆ on_ ┆ eli ┆ amt ┆ al  ┆ 6m  ┆ il  ┆ 2m  ┆ 4m  ┆ e_r ┆ _il ┆ --- ┆ 2m  ┆ 4m  ┆ c   ┆ --- ┆ _hi ┆ str ┆ tl  ┆ 12m ┆ pas ┆ al  ┆ o_b ┆ --- ┆ _wi ┆ nt  ┆ d_i ┆ d_r ┆ nt_ ┆ nt_ ┆ --- ┆ e_r ┆ e_r ┆ e_r ┆ e_r ┆ _ev ┆ bc_ ┆ rev ┆ ts  ┆ --- ┆ --- ┆ v_t ┆ cct ┆ l_b ┆ --- ┆ 0dp ┆ dpd ┆ g_d ┆ _pa ┆ r_d ┆ c_g ┆ ank ┆ --- ┆ ed_ ┆ _ex ┆ lim ┆ hig ┆ us  ┆ --- │
│ i64 ┆ --- ┆ inv ┆     ┆ f64 ┆ --- ┆     ┆ str ┆ --- ┆ ip  ┆ --- ┆ _st ┆ str ┆ str ┆ --- ┆     ┆ --- ┆ lin ┆ ow  ┆ igh ┆ hs  ┆ ast ┆ ast ┆ i64 ┆ i64 ┆ i64 ┆ --- ┆ i64 ┆ _st ┆ 12_ ┆ ast ┆ typ ┆ nq  ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ cnt ┆ --- ┆ str ┆ --- ┆ --- ┆ --- ┆ str ┆ _li ┆     ┆ --- ┆ --- ┆ t_2 ┆ --- ┆ uy  ┆ str ┆ thi ┆ --- ┆ l_a ┆ ev_ ┆ rev ┆ tl  ┆ str ┆ ece ┆ ece ┆ ece ┆ ece ┆ er_ ┆ tl  ┆ _tl ┆ --- ┆ str ┆ str ┆ l   ┆ s   ┆ al_ ┆ str ┆ d_2 ┆ --- ┆ pd_ ┆ st_ ┆ lq  ┆ t_7 ┆ rup ┆ i64 ┆ lim ┆ _mo ┆ it  ┆ h_c ┆ --- ┆ dat │
│     ┆ i64 ┆ --- ┆     ┆     ┆ f64 ┆     ┆     ┆ i8  ┆ --- ┆ f64 ┆ atu ┆     ┆     ┆ str ┆     ┆ i64 ┆ e   ┆ --- ┆ --- ┆ --- ┆ _de ┆ _re ┆     ┆     ┆     ┆ f64 ┆     ┆ atu ┆ mth ┆ _ma ┆ e   ┆ --- ┆ str ┆ str ┆ str ┆ str ┆ str ┆ str ┆ _il ┆ str ┆     ┆ str ┆ str ┆ str ┆     ┆ m   ┆     ┆ str ┆ str ┆ 4mt ┆ str ┆ --- ┆     ┆ n_1 ┆ i64 ┆ cct ┆ tl_ ┆ _tl ┆ --- ┆     ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ 120 ┆ --- ┆ --- ┆ str ┆     ┆     ┆ --- ┆ --- ┆ gt_ ┆     ┆ m   ┆ str ┆ 24m ┆ 12m ┆ --- ┆ 5   ┆ tci ┆     ┆ --- ┆ rt  ┆ --- ┆ red ┆ str ┆ e   │
│     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ i64 ┆ i64 ┆ i64 ┆ lin ┆ cor ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ s_e ┆ jor ┆ --- ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ hs  ┆     ┆ str ┆     ┆ 2_m ┆     ┆ --- ┆ op  ┆ _op ┆ str ┆     ┆ bc  ┆ bc_ ┆ inq ┆ rev ┆ _pd ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆ str ┆ 0   ┆     ┆ --- ┆     ┆ --- ┆ --- ┆ str ┆ --- ┆ es  ┆     ┆ str ┆ --- ┆ str ┆ it_ ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ q   ┆ d   ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ x_m ┆ _de ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ ths ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ dlq ┆ --- ┆ ol_ ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆ --- ┆     ┆     ┆ str ┆     ┆ lim ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆ ed  ┆ rog ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆ --- ┆ str ┆ del ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆ it  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ inq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 120 ┆ 120 ┆ 120 ┆ 36  ┆ 7.9 ┆ 375 ┆ A   ┆ A5  ┆ nul ┆ OWN ┆ 420 ┆ Sou ┆ deb ┆ 923 ┆ CA  ┆ 27. ┆ 0   ┆ Jun ┆ 715 ┆ 719 ┆ 0   ┆ nul ┆ 80  ┆ 9   ┆ 1   ┆ 114 ┆ 37. ┆ 16  ┆ w   ┆ 0   ┆ nul ┆ Ind ┆ 0   ┆ 0   ┆ 305 ┆ 1   ┆ 2   ┆ 1   ┆ 3   ┆ 8   ┆ 190 ┆ 73  ┆ 2   ┆ 4   ┆ 711 ┆ 53  ┆ 310 ┆ 1   ┆ 1   ┆ 2   ┆ 7   ┆ 338 ┆ 714 ┆ 53. ┆ 0   ┆ 0   ┆ 131 ┆ 255 ┆ 1   ┆ 1   ┆ 0   ┆ 14  ┆ nul ┆ 8   ┆ nul ┆ 0   ┆ 2   ┆ 6   ┆ 2   ┆ 2   ┆ 7   ┆ 7   ┆ 9   ┆ 6   ┆ 9   ┆ 0   ┆ 0   ┆ 0   ┆ 3   ┆ 100 ┆ 0   ┆ 1   ┆ 0   ┆ 571 ┆ 305 ┆ 155 ┆ 261 ┆ pai ┆ 201 │
│ 00  ┆ 00  ┆ 00. ┆     ┆ 7   ┆ .88 ┆     ┆     ┆ l   ┆     ┆ 00. ┆ rce ┆ t_c ┆ xx  ┆     ┆ 74  ┆     ┆ -19 ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆ 57  ┆ 0   ┆     ┆     ┆     ┆ l   ┆ ivi ┆     ┆     ┆ 02  ┆     ┆     ┆     ┆     ┆     ┆ 45  ┆     ┆     ┆     ┆ 7   ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆ 9   ┆ 4   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 80  ┆ 02  ┆ 00  ┆ 80  ┆ d   ┆ 7-0 │
│     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ Ver ┆ ons ┆     ┆     ┆     ┆     ┆ 96  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dua ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ifi ┆ oli ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 100 ┆ 100 ┆ 100 ┆ 36  ┆ 9.4 ┆ 320 ┆ B   ┆ B1  ┆ 3   ┆ MOR ┆ 550 ┆ Not ┆ deb ┆ 971 ┆ OR  ┆ 18. ┆ 0   ┆ Sep ┆ 695 ┆ 699 ┆ 0   ┆ 68  ┆ 99  ┆ 7   ┆ 1   ┆ 718 ┆ 57. ┆ 10  ┆ w   ┆ 0   ┆ nul ┆ Ind ┆ 0   ┆ 0   ┆ 340 ┆ 0   ┆ 4   ┆ 1   ┆ 2   ┆ 10  ┆ 209 ┆ 75  ┆ 0   ┆ 0   ┆ 684 ┆ 68  ┆ 125 ┆ 1   ┆ 1   ┆ 1   ┆ 3   ┆ 486 ┆ 365 ┆ 65. ┆ 0   ┆ 0   ┆ 144 ┆ 73  ┆ 49  ┆ 10  ┆ 2   ┆ 49  ┆ nul ┆ 8   ┆ 68  ┆ 0   ┆ 1   ┆ 2   ┆ 1   ┆ 1   ┆ 5   ┆ 2   ┆ 3   ┆ 2   ┆ 7   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 100 ┆ 0   ┆ 1   ┆ 0   ┆ 315 ┆ 216 ┆ 105 ┆ 175 ┆ pai ┆ 201 │
│ 00  ┆ 00  ┆ 00. ┆     ┆ 4   ┆ .05 ┆     ┆     ┆     ┆ TGA ┆ 00. ┆ Ver ┆ t_c ┆ xx  ┆     ┆ 79  ┆     ┆ -20 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆ 5   ┆     ┆     ┆     ┆ l   ┆ ivi ┆     ┆     ┆ 607 ┆     ┆     ┆     ┆     ┆     ┆ 187 ┆     ┆     ┆     ┆ 7   ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆ 58  ┆ 3   ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 034 ┆ 375 ┆ 00  ┆ 048 ┆ d   ┆ 7-0 │
│     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆ GE  ┆ 0   ┆ ifi ┆ ons ┆     ┆     ┆     ┆     ┆ 05  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dua ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ oli ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 800 ┆ 800 ┆ 800 ┆ 36  ┆ 16. ┆ 281 ┆ C   ┆ C5  ┆ 0   ┆ MOR ┆ 120 ┆ Not ┆ deb ┆ 136 ┆ NY  ┆ 20. ┆ 0   ┆ Sep ┆ 700 ┆ 704 ┆ 1   ┆ 64  ┆ nul ┆ 8   ┆ 0   ┆ 190 ┆ 92. ┆ 34  ┆ w   ┆ 0   ┆ nul ┆ Joi ┆ 0   ┆ 0   ┆ 388 ┆ 2   ┆ 3   ┆ 2   ┆ 5   ┆ 6   ┆ 835 ┆ 85  ┆ 0   ┆ 0   ┆ 0   ┆ 88  ┆ 206 ┆ 1   ┆ 24  ┆ 2   ┆ 6   ┆ 555 ┆ nul ┆ nul ┆ 0   ┆ 0   ┆ 137 ┆ 276 ┆ 34  ┆ 6   ┆ 6   ┆ 152 ┆ nul ┆ 3   ┆ nul ┆ 0   ┆ 0   ┆ 3   ┆ 1   ┆ 2   ┆ 19  ┆ 4   ┆ 9   ┆ 3   ┆ 8   ┆ 0   ┆ 0   ┆ 0   ┆ 3   ┆ 97. ┆ nul ┆ 0   ┆ 0   ┆ 400 ┆ 102 ┆ 0   ┆ 899 ┆ pai ┆ 201 │
│ 0   ┆ 0   ┆ 0.0 ┆     ┆ 02  ┆ .34 ┆     ┆     ┆     ┆ TGA ┆ 000 ┆ Ver ┆ t_c ┆ xx  ┆     ┆ 36  ┆     ┆ -19 ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ 15  ┆ 3   ┆     ┆     ┆     ┆ l   ┆ nt  ┆     ┆     ┆ 595 ┆     ┆     ┆     ┆     ┆     ┆ 72  ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆ 14  ┆ l   ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ l   ┆     ┆     ┆ 558 ┆ 587 ┆     ┆ 58  ┆ d   ┆ 7-0 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GE  ┆ .0  ┆ ifi ┆ ons ┆     ┆     ┆     ┆     ┆ 94  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ App ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ oli ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 128 ┆ 128 ┆ 128 ┆ 36  ┆ 13. ┆ 434 ┆ C   ┆ C2  ┆ 5   ┆ REN ┆ 900 ┆ Not ┆ deb ┆ 799 ┆ TX  ┆ 22. ┆ 0   ┆ Dec ┆ 660 ┆ 664 ┆ 2   ┆ 43  ┆ nul ┆ 10  ┆ 0   ┆ 126 ┆ 86. ┆ 23  ┆ w   ┆ 0   ┆ 94  ┆ Ind ┆ 0   ┆ 0   ┆ 933 ┆ 2   ┆ 3   ┆ 2   ┆ 3   ┆ 6   ┆ 807 ┆ 91  ┆ 1   ┆ 3   ┆ 377 ┆ 86  ┆ 147 ┆ 0   ┆ 1   ┆ 2   ┆ 6   ┆ 103 ┆ 245 ┆ 86  ┆ 0   ┆ 0   ┆ 154 ┆ 345 ┆ 5   ┆ 5   ┆ 0   ┆ 5   ┆ nul ┆ 5   ┆ nul ┆ 0   ┆ 6   ┆ 6   ┆ 6   ┆ 6   ┆ 15  ┆ 6   ┆ 8   ┆ 6   ┆ 9   ┆ nul ┆ 0   ┆ 0   ┆ 3   ┆ 83  ┆ 83. ┆ 0   ┆ 0   ┆ 103 ┆ 933 ┆ 147 ┆ 882 ┆ pai ┆ 201 │
│ 00  ┆ 00  ┆ 00. ┆     ┆ 59  ┆ .93 ┆     ┆     ┆     ┆ T   ┆ 00. ┆ Ver ┆ t_c ┆ xx  ┆     ┆ 63  ┆     ┆ -19 ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ 60  ┆ 0   ┆     ┆     ┆     ┆     ┆ ivi ┆     ┆     ┆ 75  ┆     ┆     ┆     ┆     ┆     ┆ 15  ┆     ┆     ┆     ┆ 7   ┆     ┆ 50  ┆     ┆     ┆     ┆     ┆ 75  ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆ 040 ┆ 75  ┆ 50  ┆ 90  ┆ d   ┆ 7-0 │
│     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ ifi ┆ ons ┆     ┆     ┆     ┆     ┆ 88  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dua ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ oli ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [20]:
# current data feature
data_profile_now = data_profile.filter(pl.col("feature").is_in(df.collect_schema().names()))

# dtype mapping
dtype_map = {
    "Int64": pl.Int64,
    "Float64": pl.Float64,
    "string": pl.String,
    "category": pl.Categorical,
    "datetime64[ns]": pl.Date,
}

# define feature and their cast
feature_list = data_profile_now["feature"].to_list()

dtype_lists = data_profile_now["cast"].to_list()
dtype_lists = [dtype_map[i] for i in dtype_lists]

# cast
cast_exec = [pl.col(column).cast(dtype, strict=False)
            for column, dtype in zip(feature_list, dtype_lists)
            if column != "earliest_cr_line"]

cast_exec = cast_exec + [pl.col("earliest_cr_line").str.strptime(pl.Date, "%b-%Y", strict=False)]

df = df.with_columns(cast_exec)

In [21]:
df.head(5).collect()

shape: (5, 89)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ loa ┆ fun ┆ fun ┆ ter ┆ int ┆ ins ┆ gra ┆ sub ┆ emp ┆ hom ┆ ann ┆ ver ┆ pur ┆ zip ┆ add ┆ dti ┆ del ┆ ear ┆ fic ┆ fic ┆ inq ┆ mth ┆ mth ┆ ope ┆ pub ┆ rev ┆ rev ┆ tot ┆ ini ┆ col ┆ mth ┆ app ┆ acc ┆ tot ┆ tot ┆ ope ┆ ope ┆ ope ┆ ope ┆ mth ┆ tot ┆ il_ ┆ ope ┆ ope ┆ max ┆ all ┆ tot ┆ inq ┆ tot ┆ inq ┆ acc ┆ avg ┆ bc_ ┆ bc_ ┆ cha ┆ del ┆ mo_ ┆ mo_ ┆ mo_ ┆ mo_ ┆ mor ┆ mth ┆ mth ┆ mth ┆ mth ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ pct ┆ per ┆ pub ┆ tax ┆ tot ┆ tot ┆ tot ┆ tot ┆ loa ┆ iss │
│ n_a ┆ ded ┆ ded ┆ m   ┆ _ra ┆ tal ┆ de  ┆ _gr ┆ _le ┆ e_o ┆ ual ┆ ifi ┆ pos ┆ _co ┆ r_s ┆ --- ┆ inq ┆ lie ┆ o_r ┆ o_r ┆ _la ┆ s_s ┆ s_s ┆ n_a ┆ _re ┆ ol_ ┆ ol_ ┆ al_ ┆ tia ┆ lec ┆ s_s ┆ lic ┆ _no ┆ _co ┆ _cu ┆ n_a ┆ n_a ┆ n_i ┆ n_i ┆ s_s ┆ al_ ┆ uti ┆ n_r ┆ n_r ┆ _ba ┆ _ut ┆ al_ ┆ _fi ┆ al_ ┆ _la ┆ _op ┆ _cu ┆ ope ┆ uti ┆ rge ┆ inq ┆ sin ┆ sin ┆ sin ┆ sin ┆ t_a ┆ s_s ┆ s_s ┆ s_s ┆ s_s ┆ _ac ┆ _ac ┆ _ac ┆ _bc ┆ _bc ┆ _il ┆ _op ┆ _re ┆ _re ┆ _sa ┆ _tl ┆ _tl ┆ _tl ┆ _tl ┆ _tl ┆ cen ┆ _re ┆ _li ┆ _hi ┆ al_ ┆ al_ ┆ al_ ┆ n_s ┆ ue_ │
│ mnt ┆ _am ┆ _am ┆ --- ┆ te  ┆ lme ┆ --- ┆ ade ┆ ngt ┆ wne ┆ _in ┆ cat ┆ e   ┆ de  ┆ tat ┆ f64 ┆ _2y ┆ st_ ┆ ang ┆ ang ┆ st_ ┆ inc ┆ inc ┆ cc  ┆ c   ┆ bal ┆ uti ┆ acc ┆ l_l ┆ tio ┆ inc ┆ ati ┆ w_d ┆ ll_ ┆ r_b ┆ cc_ ┆ ct_ ┆ l_1 ┆ l_2 ┆ inc ┆ bal ┆ l   ┆ v_1 ┆ v_2 ┆ l_b ┆ il  ┆ rev ┆ --- ┆ cu_ ┆ st_ ┆ en_ ┆ r_b ┆ n_t ┆ l   ┆ off ┆ _am ┆ _ol ┆ _ol ┆ _rc ┆ _rc ┆ cc  ┆ inc ┆ inc ┆ inc ┆ inc ┆ cts ┆ tv_ ┆ tv_ ┆ _sa ┆ _tl ┆ _tl ┆ _re ┆ v_a ┆ v_t ┆ ts  ┆ _12 ┆ _30 ┆ _90 ┆ _op ┆ _nv ┆ t_b ┆ c_b ┆ ens ┆ _cr ┆ bal ┆ bc_ ┆ il_ ┆ tat ┆ d   │
│ --- ┆ nt  ┆ nt_ ┆ i64 ┆ --- ┆ nt  ┆ cat ┆ --- ┆ h   ┆ rsh ┆ c   ┆ ion ┆ --- ┆ --- ┆ e   ┆     ┆ rs  ┆ cr_ ┆ e_l ┆ e_h ┆ 6mt ┆ e_l ┆ e_l ┆ --- ┆ --- ┆ --- ┆ l   ┆ --- ┆ ist ┆ ns_ ┆ e_l ┆ on_ ┆ eli ┆ amt ┆ al  ┆ 6m  ┆ il  ┆ 2m  ┆ 4m  ┆ e_r ┆ _il ┆ --- ┆ 2m  ┆ 4m  ┆ c   ┆ --- ┆ _hi ┆ i64 ┆ tl  ┆ 12m ┆ pas ┆ al  ┆ o_b ┆ --- ┆ _wi ┆ nt  ┆ d_i ┆ d_r ┆ nt_ ┆ nt_ ┆ --- ┆ e_r ┆ e_r ┆ e_r ┆ e_r ┆ _ev ┆ bc_ ┆ rev ┆ ts  ┆ --- ┆ --- ┆ v_t ┆ cct ┆ l_b ┆ --- ┆ 0dp ┆ dpd ┆ g_d ┆ _pa ┆ r_d ┆ c_g ┆ ank ┆ --- ┆ ed_ ┆ _ex ┆ lim ┆ hig ┆ us  ┆ --- │
│ i64 ┆ --- ┆ inv ┆     ┆ f64 ┆ --- ┆     ┆ cat ┆ --- ┆ ip  ┆ --- ┆ _st ┆ cat ┆ str ┆ --- ┆     ┆ --- ┆ lin ┆ ow  ┆ igh ┆ hs  ┆ ast ┆ ast ┆ i64 ┆ i64 ┆ f64 ┆ --- ┆ i64 ┆ _st ┆ 12_ ┆ ast ┆ typ ┆ nq  ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ cnt ┆ --- ┆ f64 ┆ --- ┆ --- ┆ --- ┆ f64 ┆ _li ┆     ┆ --- ┆ --- ┆ t_2 ┆ --- ┆ uy  ┆ f64 ┆ thi ┆ --- ┆ l_a ┆ ev_ ┆ rev ┆ tl  ┆ i64 ┆ ece ┆ ece ┆ ece ┆ ece ┆ er_ ┆ tl  ┆ _tl ┆ --- ┆ i64 ┆ i64 ┆ l   ┆ s   ┆ al_ ┆ i64 ┆ d_2 ┆ --- ┆ pd_ ┆ st_ ┆ lq  ┆ t_7 ┆ rup ┆ i64 ┆ lim ┆ _mo ┆ it  ┆ h_c ┆ --- ┆ dat │
│     ┆ i64 ┆ --- ┆     ┆     ┆ f64 ┆     ┆     ┆ i64 ┆ --- ┆ f64 ┆ atu ┆     ┆     ┆ cat ┆     ┆ i64 ┆ e   ┆ --- ┆ --- ┆ --- ┆ _de ┆ _re ┆     ┆     ┆     ┆ f64 ┆     ┆ atu ┆ mth ┆ _ma ┆ e   ┆ --- ┆ f64 ┆ f64 ┆ i64 ┆ i64 ┆ i64 ┆ i64 ┆ _il ┆ f64 ┆     ┆ i64 ┆ i64 ┆ f64 ┆     ┆ m   ┆     ┆ i64 ┆ i64 ┆ 4mt ┆ f64 ┆ --- ┆     ┆ n_1 ┆ f64 ┆ cct ┆ tl_ ┆ _tl ┆ --- ┆     ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ 120 ┆ --- ┆ --- ┆ i64 ┆     ┆     ┆ --- ┆ --- ┆ gt_ ┆     ┆ m   ┆ i64 ┆ 24m ┆ 12m ┆ --- ┆ 5   ┆ tci ┆     ┆ --- ┆ rt  ┆ --- ┆ red ┆ cat ┆ e   │
│     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ cat ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ i64 ┆ i64 ┆ i64 ┆ lin ┆ cor ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ s_e ┆ jor ┆ --- ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ hs  ┆     ┆ f64 ┆     ┆ 2_m ┆     ┆ --- ┆ op  ┆ _op ┆ i64 ┆     ┆ bc  ┆ bc_ ┆ inq ┆ rev ┆ _pd ┆ i64 ┆ i64 ┆     ┆     ┆     ┆ i64 ┆ i64 ┆ 0   ┆     ┆ --- ┆     ┆ --- ┆ --- ┆ f64 ┆ --- ┆ es  ┆     ┆ f64 ┆ --- ┆ f64 ┆ it_ ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     ┆     ┆ q   ┆ d   ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ x_m ┆ _de ┆ cat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ ths ┆     ┆ i64 ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ dlq ┆ --- ┆ ol_ ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ i64 ┆     ┆ i64 ┆ i64 ┆     ┆ f64 ┆ --- ┆     ┆     ┆ f64 ┆     ┆ lim ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cat ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ cat ┆ ed  ┆ rog ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆ i64 ┆ --- ┆ i64 ┆ del ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆ it  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆ inq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 120 ┆ 120 ┆ 120 ┆ 36  ┆ 7.9 ┆ 375 ┆ A   ┆ A5  ┆ nul ┆ OWN ┆ 420 ┆ Sou ┆ deb ┆ 923 ┆ CA  ┆ 27. ┆ 0   ┆ 199 ┆ 715 ┆ 719 ┆ 0   ┆ nul ┆ 80  ┆ 9   ┆ 1   ┆ 114 ┆ 37. ┆ 16  ┆ w   ┆ 0   ┆ nul ┆ Ind ┆ 0   ┆ 0.0 ┆ 305 ┆ 1   ┆ 2   ┆ 1   ┆ 3   ┆ 8   ┆ 190 ┆ 73. ┆ 2   ┆ 4   ┆ 711 ┆ 53. ┆ 310 ┆ 1   ┆ 1   ┆ 2   ┆ 7   ┆ 338 ┆ 714 ┆ 53. ┆ 0   ┆ 0.0 ┆ 131 ┆ 255 ┆ 1   ┆ 1   ┆ 0   ┆ 14  ┆ nul ┆ 8   ┆ nul ┆ 0   ┆ 2   ┆ 6   ┆ 2   ┆ 2   ┆ 7   ┆ 7   ┆ 9   ┆ 6   ┆ 9   ┆ 0   ┆ 0   ┆ 0   ┆ 3   ┆ 100 ┆ 0.0 ┆ 1   ┆ 0   ┆ 571 ┆ 305 ┆ 155 ┆ 261 ┆ pai ┆ 201 │
│ 00  ┆ 00  ┆ 00. ┆     ┆ 7   ┆ .88 ┆     ┆     ┆ l   ┆     ┆ 00. ┆ rce ┆ t_c ┆ xx  ┆     ┆ 74  ┆     ┆ 6-0 ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆ 57. ┆ 0   ┆     ┆     ┆     ┆ l   ┆ ivi ┆     ┆     ┆ 02. ┆     ┆     ┆     ┆     ┆     ┆ 45. ┆ 0   ┆     ┆     ┆ 7.0 ┆ 0   ┆ 00. ┆     ┆     ┆     ┆     ┆ 9.0 ┆ 4.0 ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆     ┆     ┆     ┆ 80. ┆ 02. ┆ 00. ┆ 80. ┆ d   ┆ 7-0 │
│     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ Ver ┆ ons ┆     ┆     ┆     ┆     ┆ 6-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆ dua ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆     ┆ 9-0 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ifi ┆ oli ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 100 ┆ 100 ┆ 100 ┆ 36  ┆ 9.4 ┆ 320 ┆ B   ┆ B1  ┆ 3   ┆ MOR ┆ 550 ┆ Not ┆ deb ┆ 971 ┆ OR  ┆ 18. ┆ 0   ┆ 200 ┆ 695 ┆ 699 ┆ 0   ┆ 68  ┆ 99  ┆ 7   ┆ 1   ┆ 718 ┆ 57. ┆ 10  ┆ w   ┆ 0   ┆ nul ┆ Ind ┆ 0   ┆ 0.0 ┆ 340 ┆ 0   ┆ 4   ┆ 1   ┆ 2   ┆ 10  ┆ 209 ┆ 75. ┆ 0   ┆ 0   ┆ 684 ┆ 68. ┆ 125 ┆ 1   ┆ 1   ┆ 1   ┆ 3   ┆ 486 ┆ 365 ┆ 65. ┆ 0   ┆ 0.0 ┆ 144 ┆ 73  ┆ 49  ┆ 10  ┆ 2   ┆ 49  ┆ nul ┆ 8   ┆ 68  ┆ 0   ┆ 1   ┆ 2   ┆ 1   ┆ 1   ┆ 5   ┆ 2   ┆ 3   ┆ 2   ┆ 7   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 100 ┆ 0.0 ┆ 1   ┆ 0   ┆ 315 ┆ 216 ┆ 105 ┆ 175 ┆ pai ┆ 201 │
│ 00  ┆ 00  ┆ 00. ┆     ┆ 4   ┆ .05 ┆     ┆     ┆     ┆ TGA ┆ 00. ┆ Ver ┆ t_c ┆ xx  ┆     ┆ 79  ┆     ┆ 5-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8.0 ┆ 5   ┆     ┆     ┆     ┆ l   ┆ ivi ┆     ┆     ┆ 607 ┆     ┆     ┆     ┆     ┆     ┆ 187 ┆ 0   ┆     ┆     ┆ 7.0 ┆ 0   ┆ 00. ┆     ┆     ┆     ┆     ┆ 58. ┆ 3.0 ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆     ┆     ┆     ┆ 034 ┆ 375 ┆ 00. ┆ 048 ┆ d   ┆ 7-0 │
│     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆ GE  ┆ 0   ┆ ifi ┆ ons ┆     ┆     ┆     ┆     ┆ 9-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dua ┆     ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆ .0  ┆ 0   ┆ .0  ┆     ┆ 9-0 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ oli ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 800 ┆ 800 ┆ 800 ┆ 36  ┆ 16. ┆ 281 ┆ C   ┆ C5  ┆ 0   ┆ MOR ┆ 120 ┆ Not ┆ deb ┆ 136 ┆ NY  ┆ 20. ┆ 0   ┆ 199 ┆ 700 ┆ 704 ┆ 1   ┆ 64  ┆ nul ┆ 8   ┆ 0   ┆ 190 ┆ 92. ┆ 34  ┆ w   ┆ 0   ┆ nul ┆ Joi ┆ 0   ┆ 0.0 ┆ 388 ┆ 2   ┆ 3   ┆ 2   ┆ 5   ┆ 6   ┆ 835 ┆ 85. ┆ 0   ┆ 0   ┆ 0.0 ┆ 88. ┆ 206 ┆ 1   ┆ 24  ┆ 2   ┆ 6   ┆ 555 ┆ nul ┆ nul ┆ 0   ┆ 0.0 ┆ 137 ┆ 276 ┆ 34  ┆ 6   ┆ 6   ┆ 152 ┆ nul ┆ 3   ┆ nul ┆ 0   ┆ 0   ┆ 3   ┆ 1   ┆ 2   ┆ 19  ┆ 4   ┆ 9   ┆ 3   ┆ 8   ┆ 0   ┆ 0   ┆ 0   ┆ 3   ┆ 97. ┆ nul ┆ 0   ┆ 0   ┆ 400 ┆ 102 ┆ 0.0 ┆ 899 ┆ pai ┆ 201 │
│ 0   ┆ 0   ┆ 0.0 ┆     ┆ 02  ┆ .34 ┆     ┆     ┆     ┆ TGA ┆ 000 ┆ Ver ┆ t_c ┆ xx  ┆     ┆ 36  ┆     ┆ 4-0 ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ 15. ┆ 3   ┆     ┆     ┆     ┆ l   ┆ nt  ┆     ┆     ┆ 595 ┆     ┆     ┆     ┆     ┆     ┆ 72. ┆ 0   ┆     ┆     ┆     ┆ 0   ┆ 00. ┆     ┆     ┆     ┆     ┆ 14. ┆ l   ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ l   ┆     ┆     ┆ 558 ┆ 587 ┆     ┆ 58. ┆ d   ┆ 7-0 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GE  ┆ .0  ┆ ifi ┆ ons ┆     ┆     ┆     ┆     ┆ 9-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆ App ┆     ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆ .0  ┆     ┆ 0   ┆     ┆ 9-0 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ oli ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 128 ┆ 128 ┆ 128 ┆ 36  ┆ 13. ┆ 434 ┆ C   ┆ C2  ┆ 5   ┆ REN ┆ 900 ┆ Not ┆ deb ┆ 799 ┆ TX  ┆ 22. ┆ 0   ┆ 198 ┆ 660 ┆ 664 ┆ 2   ┆ 43  ┆ nul ┆ 10  ┆ 0   ┆ 126 ┆ 86. ┆ 23  ┆ w   ┆ 0   ┆ 94  ┆ Ind ┆ 0   ┆ 0.0 ┆ 933 ┆ 2   ┆ 3   ┆ 2   ┆ 3   ┆ 6   ┆ 807 ┆ 91. ┆ 1   ┆ 3   ┆ 377 ┆ 86. ┆ 147 ┆ 0   ┆ 1   ┆ 2   ┆ 6   ┆ 103 ┆ 245 ┆ 86. ┆ 0   ┆ 0.0 ┆ 154 ┆ 345 ┆ 5   ┆ 5   ┆ 0   ┆ 5   ┆ nul ┆ 5   ┆ nul ┆ 0   ┆ 6   ┆ 6   ┆ 6   ┆ 6   ┆ 15  ┆ 6   ┆ 8   ┆ 6   ┆ 9   ┆ nul ┆ 0   ┆ 0   ┆ 3   ┆ 83. ┆ 83. ┆ 0   ┆ 0   ┆ 103 ┆ 933 ┆ 147 ┆ 882 ┆ pai ┆ 201 │
│ 00  ┆ 00  ┆ 00. ┆     ┆ 59  ┆ .93 ┆     ┆     ┆     ┆ T   ┆ 00. ┆ Ver ┆ t_c ┆ xx  ┆     ┆ 63  ┆     ┆ 8-1 ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ 60. ┆ 0   ┆     ┆     ┆     ┆     ┆ ivi ┆     ┆     ┆ 75. ┆     ┆     ┆     ┆     ┆     ┆ 15. ┆ 0   ┆     ┆     ┆ 7.0 ┆ 0   ┆ 50. ┆     ┆     ┆     ┆     ┆ 75. ┆ 8.0 ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆ 0   ┆ 3   ┆     ┆     ┆ 040 ┆ 75. ┆ 50. ┆ 90. ┆ d   ┆ 7-0 │
│     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ ifi ┆ ons ┆     ┆     ┆     ┆     ┆ 2-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆ dua ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆ 0   ┆ 0   ┆ 0   ┆     ┆ 9-0 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ oli ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

## 3.6. Data Quality Check

In [22]:
def create_data_profile(
    lf: pl.LazyFrame,
    description_df: pl.DataFrame,
    unique_sample_size: int = 5,
) -> pl.DataFrame:
    """
    Create a column-level data profile from a Polars LazyFrame.

    Includes:
    - feature
    - description
    - dtype
    - count
    - null_count
    - null_pct
    - unique_count
    - unique_sample
    - mean
    - median
    - mode

    The description is retrieved from a CSV containing:
    - LoanStatNew
    - Description

    If a feature does not have a matching description,
    the description is returned as null.

    Mean and median are only calculated for numeric columns.
    """

    # ---------------------------------------------------------
    # 1. Load feature descriptions
    # ---------------------------------------------------------

    description_df = (
        description_df
        .select([
            pl.col("LoanStatNew").alias("feature"),
            pl.col("Description").alias("description"),
        ])
        .with_columns(
            pl.col("feature").cast(pl.String),
            pl.col("description").cast(pl.String),
        )
        .unique(subset=["feature"])
    )

    # ---------------------------------------------------------
    # 2. Get schema
    # ---------------------------------------------------------

    schema = lf.collect_schema()

    profile = []

    # ---------------------------------------------------------
    # 3. Profile each feature
    # ---------------------------------------------------------

    for col, dtype in tqdm(schema.items()):

        stats = (
            lf.select([
                pl.len().alias("count"),
                pl.col(col).null_count().alias("null_count"),
                pl.col(col).n_unique().alias("unique_count"),
            ])
            .collect()
            .row(0)
        )

        count, null_count, unique_count = stats

        null_pct = (
            null_count / count * 100
            if count > 0
            else 0
        )

        # -----------------------------------------------------
        # Unique sample
        # -----------------------------------------------------

        unique_sample = (
            lf.select(
                pl.col(col)
                .drop_nulls()
                .unique()
                .head(unique_sample_size)
                .alias(col)
            )
            .collect()
            .get_column(col)
            .to_list()
        )

        # -----------------------------------------------------
        # Default statistics
        # -----------------------------------------------------

        mean = None
        median = None
        mode = None

        # -----------------------------------------------------
        # Numeric statistics
        # -----------------------------------------------------

        if dtype.is_numeric():

            numeric_stats = (
                lf.select([
                    pl.col(col).mean().alias("mean"),
                    pl.col(col).median().alias("median"),
                ])
                .collect()
                .row(0)
            )

            mean, median = numeric_stats

        # -----------------------------------------------------
        # Mode
        # -----------------------------------------------------

        mode_result = (
            lf.select(
                pl.col(col)
                .drop_nulls()
                .mode()
                .head(1)
                .alias("mode")
            )
            .collect()
            .get_column("mode")
            .to_list()
        )

        if mode_result:
            mode = mode_result[0]

        # -----------------------------------------------------
        # Store profile
        # -----------------------------------------------------

        profile.append({
            "feature": col,
            "dtype": str(dtype),
            "count": count,
            "null_count": null_count,
            "null_pct": null_pct,
            "unique_count": unique_count,
            "unique_sample": str(unique_sample),
            "mean": str(mean),
            "median": str(median),
            "mode": str(mode),
        })

    # ---------------------------------------------------------
    # 4. Create profile DataFrame
    # ---------------------------------------------------------

    profile_df = pl.DataFrame(profile)

    # ---------------------------------------------------------
    # 5. Add descriptions
    # ---------------------------------------------------------

    profile_df = (
        profile_df
        .join(
            description_df,
            on="feature",
            how="left",
        )
        .select([
            "feature",
            "description",
            "dtype",
            "count",
            "null_count",
            "null_pct",
            "unique_count",
            "unique_sample",
            "mean",
            "median",
            "mode",
        ])
    )

    return profile_df

In [23]:
# # create data profile from data clean
# description_df = pl.read_excel(RAW_DIR / "lending_club/LCDataDictionary.xlsx")
# data_profile = create_data_profile(df, description_df)

# # save data profile to parquet
# data_profile.write_parquet(INTERIM_DIR / "data_profile_model_base.parquet")

# load data profile
data_profile = pl.read_parquet(INTERIM_DIR / "data_profile_model_base.parquet")

In [24]:
# prettify data display
from great_tables import GT
from IPython.display import HTML, display

table = (GT(data_profile).tab_header(title="Dataset Profile Summary"))

html = table._repr_html_()

display(HTML(f"""
<div style="
    max-height: 600px;
    overflow-y: auto;
    overflow-x: auto;
    border: 1px solid #ddd;
">
    {html}
</div>
"""))

## 3.7. Save File

In [25]:
df.sink_parquet(PROCESSED_DIR / "modelling_base.parquet")

## 3.8. Summary

In [46]:
# preparation summary

# define temp variable
lf_miss = lf.select(pl.sum_horizontal(pl.all().null_count())).collect().item()
lf_cell = lf.select(pl.len()).collect().item() * len(lf.collect_schema())

df_miss = df.select(pl.sum_horizontal(pl.all().null_count())).collect().item()
df_cell = df.select(pl.len()).collect().item() * len(df.collect_schema())

# summary
summary = pl.DataFrame({
    "metric": [
        "Rows",
        "Columns",
        "Date range",
        "Default rate",
        "Missing cells",
        "Missing cell rate",
    ],
    "before": [
        lf.select(pl.len()).collect().item(),
        len(lf.collect_schema()),
        str(lf.select(pl.col("issue_d").str.strptime(pl.Date, "%b-%Y", strict=False).min()).collect().item()),
        lf.select((pl.col("loan_status")
                   .is_in(["Charged Off", "Default", "Does not meet the credit policy. Status:Charged Off"]))
                   .cast(pl.Float64).mean().round(4) * 100.0).collect().item(),
        lf_miss,
        round((lf_miss / lf_cell) * 100.0, 2),
    ],
    "after": [
        df.select(pl.len()).collect().item(),
        len(df.collect_schema()),
        str(df.select(pl.col("issue_d").min()).collect().item()),
        df.select((pl.col("loan_status")=="default").cast(pl.Float64).mean().round(4) * 100.0).collect().item(),
        df_miss,
        round((df_miss / df_cell) * 100.0, 2),
        
    ]}, strict=False)

summary

shape: (6, 3)
┌───────────────────┬────────────┬────────────┐
│ metric            ┆ before     ┆ after      │
│ ---               ┆ ---        ┆ ---        │
│ str               ┆ str        ┆ str        │
╞═══════════════════╪════════════╪════════════╡
│ Rows              ┆ 2925493    ┆ 994341     │
│ Columns           ┆ 142        ┆ 89         │
│ Date range        ┆ 2007-06-01 ┆ 2016-01-01 │
│ Default rate      ┆ 12.43      ┆ 20.74      │
│ Missing cells     ┆ 107893231  ┆ 4261315    │
│ Missing cell rate ┆ 25.97      ┆ 4.82       │
└───────────────────┴────────────┴────────────┘