In [1]:
# import libraries
import polars as pl
from datetime import date
from tqdm.notebook import tqdm
import plotly.express as px

pl.Config.set_tbl_rows(20)
pl.Config.set_tbl_cols(-1)
pl.Config.set_fmt_str_lengths(100)
pl.Config.set_tbl_width_chars(200)

# data path
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent.parent))

from src.config import RAW_DIR, INTERIM_DIR, PROCESSED_DIR, DOCS_DIR

In [2]:
# load data
lf = pl.scan_csv(
    RAW_DIR / "lending_club/Loan_status_2007-2020Q3.gzip",
    infer_schema_length=10000,
    ignore_errors=True)

# 7. Feature Engineering

**Main Objective**

Transform the selected origination-time features into a model-ready representation while preserving predictive information, interpretability, and leakage control.

## 7.1 Feature Selection

In [3]:
KEEP_FEATURE = ['loan_amnt',
                'term',
                'int_rate',
                'grade',
                'emp_length',
                'home_ownership',
                'annual_inc',
                'verification_status',
                'purpose',
                'addr_state',
                'dti',
                'delinq_2yrs',
                'earliest_cr_line',
                'fico_range_low',
                'inq_last_6mths',
                'mths_since_last_record',
                'pub_rec',
                'revol_util',
                'total_acc',
                'initial_list_status',
                'collections_12_mths_ex_med',
                'mths_since_last_major_derog',
                'application_type',
                'tot_coll_amt',
                'tot_cur_bal',
                'open_act_il',
                'open_il_12m',
                'mths_since_rcnt_il',
                'total_bal_il',
                'il_util',
                'open_rv_24m',
                'max_bal_bc',
                'all_util',
                'inq_fi',
                'total_cu_tl',
                'inq_last_12m',
                'mo_sin_old_il_acct',
                'mo_sin_old_rev_tl_op',
                'mo_sin_rcnt_rev_tl_op',
                'mo_sin_rcnt_tl',
                'mort_acc',
                'mths_since_recent_bc',
                'mths_since_recent_inq',
                'num_accts_ever_120_pd',
                'num_actv_rev_tl',
                'num_il_tl',
                'num_tl_120dpd_2m',
                'num_tl_90g_dpd_24m',
                'num_tl_op_past_12m',
                'pct_tl_nvr_dlq',
                'pub_rec_bankruptcies',
                'total_bc_limit']

TARGET = "loan_status"
PERIOD_COL = "issue_d"
TARGET_ENG = "default"

FILTER_FEATURE = KEEP_FEATURE + [TARGET, PERIOD_COL]

In [4]:
df = lf.select(FILTER_FEATURE)

In [5]:
len(df.collect_schema())

54

## 7.2 Value Selection (Timeframe and Loan Status)

In [6]:
# filter date
df = (df
        .with_columns(pl.col("issue_d").str.strptime(pl.Date, "%b-%Y", strict=False).alias("issue_d"))  # cast date
        .filter(pl.col("issue_d") >= date(2016, 1, 1))                                                  # filter out data before 2016
    )

In [7]:
# filter loan status
LOAN_STATUS_MAP = {
    "Charged Off" : 1,
    "Default" : 1,
    "Does not meet the credit policy. Status:Charged Off" : 1,
    "Fully Paid" : 0,
    "Does not meet the credit policy. Status:Fully Paid" : 0
}

df = (df
      .filter(pl.col(TARGET).is_in(list(LOAN_STATUS_MAP.keys())))  # filter resolved loan status
      .with_columns(
          pl.col(TARGET)
          .replace(LOAN_STATUS_MAP)                                 # simplify loan status
          .alias(TARGET_ENG)
          .cast(pl.Int8))
)

In [8]:
df.select(pl.len()).collect()

shape: (1, 1)
┌────────┐
│ len    │
│ ---    │
│ u32    │
╞════════╡
│ 994341 │
└────────┘

In [9]:
df.head(5).collect()

shape: (5, 55)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ loa ┆ ter ┆ int ┆ gra ┆ emp ┆ hom ┆ ann ┆ ver ┆ pur ┆ add ┆ dti ┆ del ┆ ear ┆ fic ┆ inq ┆ mth ┆ pub ┆ rev ┆ tot ┆ ini ┆ col ┆ mth ┆ app ┆ tot ┆ tot ┆ ope ┆ ope ┆ mth ┆ tot ┆ il_ ┆ ope ┆ max ┆ all ┆ inq ┆ tot ┆ inq ┆ mo_ ┆ mo_ ┆ mo_ ┆ mo_ ┆ mor ┆ mth ┆ mth ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ pct ┆ pub ┆ tot ┆ loa ┆ iss ┆ def │
│ n_a ┆ m   ┆ _ra ┆ de  ┆ _le ┆ e_o ┆ ual ┆ ifi ┆ pos ┆ r_s ┆ --- ┆ inq ┆ lie ┆ o_r ┆ _la ┆ s_s ┆ _re ┆ ol_ ┆ al_ ┆ tia ┆ lec ┆ s_s ┆ lic ┆ _co ┆ _cu ┆ n_a ┆ n_i ┆ s_s ┆ al_ ┆ uti ┆ n_r ┆ _ba ┆ _ut ┆ _fi ┆ al_ ┆ _la ┆ sin ┆ sin ┆ sin ┆ sin ┆ t_a ┆ s_s ┆ s_s ┆ _ac ┆ _ac ┆ _il ┆ _tl ┆ _tl ┆ _tl ┆ _tl ┆ _re ┆ al_ ┆ n_s ┆ ue_ ┆ aul │
│ mnt ┆ --- ┆ te  ┆ --- ┆ ngt ┆ wne ┆ _in ┆ cat ┆ e   ┆ tat ┆ f64 ┆ _2y ┆ st_ ┆ ang ┆ st_ ┆ inc ┆ c   ┆ uti ┆ acc ┆ l_l ┆ tio ┆ inc ┆ ati ┆ ll_ ┆ r_b ┆ ct_ ┆ l_1 ┆ inc ┆ bal ┆ l   ┆ v_2 ┆ l_b ┆ il  ┆ --- ┆ cu_ ┆ st_ ┆ _ol ┆ _ol ┆ _rc ┆ _rc ┆ cc  ┆ inc ┆ inc ┆ cts ┆ tv_ ┆ _tl ┆ _12 ┆ _90 ┆ _op ┆ _nv ┆ c_b ┆ bc_ ┆ tat ┆ d   ┆ t   │
│ --- ┆ str ┆ --- ┆ str ┆ h   ┆ rsh ┆ c   ┆ ion ┆ --- ┆ e   ┆     ┆ rs  ┆ cr_ ┆ e_l ┆ 6mt ┆ e_l ┆ --- ┆ l   ┆ --- ┆ ist ┆ ns_ ┆ e_l ┆ on_ ┆ amt ┆ al  ┆ il  ┆ 2m  ┆ e_r ┆ _il ┆ --- ┆ 4m  ┆ c   ┆ --- ┆ str ┆ tl  ┆ 12m ┆ d_i ┆ d_r ┆ nt_ ┆ nt_ ┆ --- ┆ e_r ┆ e_r ┆ _ev ┆ rev ┆ --- ┆ 0dp ┆ g_d ┆ _pa ┆ r_d ┆ ank ┆ lim ┆ us  ┆ --- ┆ --- │
│ i64 ┆     ┆ str ┆     ┆ --- ┆ ip  ┆ --- ┆ _st ┆ str ┆ --- ┆     ┆ --- ┆ lin ┆ ow  ┆ hs  ┆ ast ┆ i64 ┆ --- ┆ i64 ┆ _st ┆ 12_ ┆ ast ┆ typ ┆ --- ┆ --- ┆ --- ┆ --- ┆ cnt ┆ --- ┆ str ┆ --- ┆ --- ┆ str ┆     ┆ --- ┆ --- ┆ l_a ┆ ev_ ┆ rev ┆ tl  ┆ str ┆ ece ┆ ece ┆ er_ ┆ _tl ┆ str ┆ d_2 ┆ pd_ ┆ st_ ┆ lq  ┆ rup ┆ it  ┆ --- ┆ dat ┆ i8  │
│     ┆     ┆     ┆     ┆ str ┆ --- ┆ f64 ┆ atu ┆     ┆ str ┆     ┆ i64 ┆ e   ┆ --- ┆ --- ┆ _re ┆     ┆ str ┆     ┆ atu ┆ mth ┆ _ma ┆ e   ┆ str ┆ str ┆ str ┆ str ┆ _il ┆ str ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆ str ┆ cct ┆ tl_ ┆ _tl ┆ --- ┆     ┆ nt_ ┆ nt_ ┆ 120 ┆ --- ┆     ┆ m   ┆ 24m ┆ 12m ┆ --- ┆ tci ┆ --- ┆ str ┆ e   ┆     │
│     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ s   ┆     ┆     ┆     ┆     ┆ --- ┆ i64 ┆ i64 ┆ cor ┆     ┆     ┆     ┆ s   ┆ s_e ┆ jor ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ op  ┆ _op ┆ str ┆     ┆ bc  ┆ inq ┆ _pd ┆ str ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ es  ┆ str ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ --- ┆ x_m ┆ _de ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ --- ┆ --- ┆     ┆     ┆ str ┆ str ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ str ┆ ed  ┆ rog ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 120 ┆ 36  ┆ 7.9 ┆ A   ┆ 10+ ┆ OWN ┆ 420 ┆ Sou ┆ deb ┆ CA  ┆ 27. ┆ 0   ┆ Jun ┆ 715 ┆ 0   ┆ 80  ┆ 1   ┆ 37% ┆ 16  ┆ w   ┆ 0   ┆ nul ┆ Ind ┆ 0   ┆ 305 ┆ 2   ┆ 1   ┆ 8   ┆ 190 ┆ 73  ┆ 4   ┆ 711 ┆ 53  ┆ 1   ┆ 1   ┆ 2   ┆ 131 ┆ 255 ┆ 1   ┆ 1   ┆ 0   ┆ 14  ┆ 8   ┆ 0   ┆ 6   ┆ 7   ┆ 0   ┆ 0   ┆ 3   ┆ 100 ┆ 1   ┆ 155 ┆ Ful ┆ 201 ┆ 0   │
│ 00  ┆ mon ┆ 7%  ┆     ┆ yea ┆     ┆ 00. ┆ rce ┆ t_c ┆     ┆ 74  ┆     ┆ -19 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ ivi ┆     ┆ 02  ┆     ┆     ┆     ┆ 45  ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ ly  ┆ 7-0 ┆     │
│     ┆ ths ┆     ┆     ┆ rs  ┆     ┆ 0   ┆ Ver ┆ ons ┆     ┆     ┆     ┆ 96  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dua ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pai ┆ 9-0 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ifi ┆ oli ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ 1   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 100 ┆ 36  ┆ 9.4 ┆ B   ┆ 3   ┆ MOR ┆ 550 ┆ Not ┆ deb ┆ OR  ┆ 18. ┆ 0   ┆ Sep ┆ 695 ┆ 0   ┆ 99  ┆ 1   ┆ 57. ┆ 10  ┆ w   ┆ 0   ┆ nul ┆ Ind ┆ 0   ┆ 340 ┆ 4   ┆ 1   ┆ 10  ┆ 209 ┆ 75  ┆ 0   ┆ 684 ┆ 68  ┆ 1   ┆ 1   ┆ 1   ┆ 144 ┆ 73  ┆ 49  ┆ 10  ┆ 2   ┆ 49  ┆ 8   ┆ 0   ┆ 2   ┆ 5   ┆ 0   ┆ 0   ┆ 1   ┆ 100 ┆ 1   ┆ 105 ┆ Ful ┆ 201 ┆ 0   │
│ 00  ┆ mon ┆ 4%  ┆     ┆ yea ┆ TGA ┆ 00. ┆ Ver ┆ t_c ┆     ┆ 79  ┆     ┆ -20 ┆     ┆     ┆     ┆     ┆ 5%  ┆     ┆     ┆     ┆ l   ┆ ivi ┆     ┆ 607 ┆     ┆     ┆     ┆ 187 ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ ly  ┆ 7-0 ┆     │
│     ┆ ths ┆     ┆     ┆ rs  ┆ GE  ┆ 0   ┆ ifi ┆ ons ┆     ┆     ┆     ┆ 05  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dua ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pai ┆ 9-0 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ oli ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ 1   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 800 ┆ 36  ┆ 16. ┆ C   ┆ < 1 ┆ MOR ┆ 120 ┆ Not ┆ deb ┆ NY  ┆ 20. ┆ 0   ┆ Sep ┆ 700 ┆ 1   ┆ nul ┆ 0   ┆ 92. ┆ 34  ┆ w   ┆ 0   ┆ nul ┆ Joi ┆ 0   ┆ 388 ┆ 3   ┆ 2   ┆ 6   ┆ 835 ┆ 85  ┆ 0   ┆ 0   ┆ 88  ┆ 1   ┆ 24  ┆ 2   ┆ 137 ┆ 276 ┆ 34  ┆ 6   ┆ 6   ┆ 152 ┆ 3   ┆ 0   ┆ 3   ┆ 19  ┆ 0   ┆ 0   ┆ 3   ┆ 97. ┆ 0   ┆ 0   ┆ Ful ┆ 201 ┆ 0   │
│ 0   ┆ mon ┆ 02% ┆     ┆ yea ┆ TGA ┆ 000 ┆ Ver ┆ t_c ┆     ┆ 36  ┆     ┆ -19 ┆     ┆     ┆ l   ┆     ┆ 3%  ┆     ┆     ┆     ┆ l   ┆ nt  ┆     ┆ 595 ┆     ┆     ┆     ┆ 72  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆ ly  ┆ 7-0 ┆     │
│     ┆ ths ┆     ┆     ┆ r   ┆ GE  ┆ .0  ┆ ifi ┆ ons ┆     ┆     ┆     ┆ 94  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ App ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pai ┆ 9-0 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ oli ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ 1   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 128 ┆ 36  ┆ 13. ┆ C   ┆ 5   ┆ REN ┆ 900 ┆ Not ┆ deb ┆ TX  ┆ 22. ┆ 0   ┆ Dec ┆ 660 ┆ 2   ┆ nul ┆ 0   ┆ 86% ┆ 23  ┆ w   ┆ 0   ┆ 94  ┆ Ind ┆ 0   ┆ 933 ┆ 3   ┆ 2   ┆ 6   ┆ 807 ┆ 91  ┆ 3   ┆ 377 ┆ 86  ┆ 0   ┆ 1   ┆ 2   ┆ 154 ┆ 345 ┆ 5   ┆ 5   ┆ 0   ┆ 5   ┆ 5   ┆ 0   ┆ 6   ┆ 15  ┆ nul ┆ 0   ┆ 3   ┆ 83  ┆ 0   ┆ 147 ┆ Ful ┆ 201 ┆ 0   │
│ 00  ┆ mon ┆ 59% ┆     ┆ yea ┆ T   ┆ 00. ┆ Ver ┆ t_c ┆     ┆ 63  ┆     ┆ -19 ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆ ivi ┆     ┆ 75  ┆     ┆     ┆     ┆ 15  ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆ 50  ┆ ly  ┆ 7-0 ┆     │
│     ┆ ths ┆     ┆     ┆ rs  ┆     ┆ 0   ┆ ifi ┆ ons ┆     ┆     ┆     ┆ 88  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dua ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pai ┆ 9-0 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ oli ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ 1   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 150 ┆ 36  ┆ 13. ┆ C   ┆ 4   ┆ MOR ┆ 180 ┆ Sou ┆ med ┆ TX  ┆ 38. ┆ 0   ┆ Dec ┆ 680 ┆ 0   ┆ nul ┆ 0   ┆ 66. ┆ 50  ┆ w   ┆ 0   ┆ nul ┆ Ind ┆ 0   ┆ 682 ┆ 4   ┆ 0   ┆ 13  ┆ 190 ┆ 79  ┆ 1   ┆ 221 ┆ 68  ┆ 2   ┆ 8   ┆ 0   ┆ 132 ┆ 489 ┆ 16  ┆ 13  ┆ 4   ┆ 16  ┆ 13  ┆ 0   ┆ 14  ┆ 17  ┆ 0   ┆ 0   ┆ 0   ┆ 100 ┆ 0   ┆ 116 ┆ Ful ┆ 201 ┆ 0   │
│ 00  ┆ mon ┆ 59% ┆     ┆ yea ┆ TGA ┆ 000 ┆ rce ┆ ica ┆     ┆ 07  ┆     ┆ -19 ┆     ┆     ┆ l   ┆     ┆ 6%  ┆     ┆     ┆     ┆ l   ┆ ivi ┆     ┆ 000 ┆     ┆     ┆     ┆ 233 ┆     ┆     ┆ 27  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 700 ┆ ly  ┆ 7-0 ┆     │
│     ┆ ths ┆     ┆     ┆ rs  ┆ GE  ┆ .0  ┆ Ver ┆ l   ┆     ┆     ┆     ┆ 76  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dua ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pai ┆ 9-0 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ifi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ 1   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

## 7.3 Data Normalization and Casting

In [10]:
# cast data type
df = df.with_columns([

    # cast term to int
    pl.col("term")
      .str.strip_chars()
      .str.replace(" months", "")
      .cast(pl.Int8, strict=False),

    # cast int_rate
    pl.col("int_rate")
      .str.strip_chars()
      .str.replace("%", "")
      .cast(pl.Float64, strict=False),

    # cast revol_util
    pl.col("revol_util")
      .str.strip_chars()
      .str.replace("%", "")
      .cast(pl.Float64, strict=False),

    # cast emp_length
    pl.col("emp_length")
      .str.strip_chars()
      .str.replace(" years", "")
      .str.replace(" year", "")
      .str.replace("< 1", "0")
      .str.replace("10+", "10")
      .cast(pl.Int8, strict=False)
])

In [11]:
CAST_FEATURE ={'loan_amnt': pl.Int64,
                'term': pl.Int64,
                'int_rate': pl.Float64,
                'grade': pl.Categorical,
                'emp_length': pl.Int64,
                'home_ownership': pl.Categorical,
                'annual_inc': pl.Float64,
                'verification_status': pl.Categorical,
                'issue_d': pl.Date,
                'loan_status': pl.Categorical,
                'purpose': pl.Categorical,
                'addr_state': pl.Categorical,
                'dti': pl.Float64,
                'delinq_2yrs': pl.Int64,
                'earliest_cr_line': pl.Date,
                'fico_range_low': pl.Int64,
                'inq_last_6mths': pl.Int64,
                'mths_since_last_record': pl.Int64,
                'pub_rec': pl.Int64,
                'revol_util': pl.Float64,
                'total_acc': pl.Int64,
                'initial_list_status': pl.Categorical,
                'collections_12_mths_ex_med': pl.Int64,
                'mths_since_last_major_derog': pl.Int64,
                'application_type': pl.Categorical,
                'tot_coll_amt': pl.Float64,
                'tot_cur_bal': pl.Float64,
                'open_act_il': pl.Int64,
                'open_il_12m': pl.Int64,
                'mths_since_rcnt_il': pl.Int64,
                'total_bal_il': pl.Float64,
                'il_util': pl.Float64,
                'open_rv_24m': pl.Int64,
                'max_bal_bc': pl.Float64,
                'all_util': pl.Float64,
                'inq_fi': pl.Int64,
                'total_cu_tl': pl.Int64,
                'inq_last_12m': pl.Int64,
                'mo_sin_old_il_acct': pl.Int64,
                'mo_sin_old_rev_tl_op': pl.Int64,
                'mo_sin_rcnt_rev_tl_op': pl.Int64,
                'mo_sin_rcnt_tl': pl.Int64,
                'mort_acc': pl.Int64,
                'mths_since_recent_bc': pl.Int64,
                'mths_since_recent_inq': pl.Int64,
                'num_accts_ever_120_pd': pl.Int64,
                'num_actv_rev_tl': pl.Int64,
                'num_il_tl': pl.Int64,
                'num_tl_120dpd_2m': pl.Int64,
                'num_tl_90g_dpd_24m': pl.Int64,
                'num_tl_op_past_12m': pl.Int64,
                'pct_tl_nvr_dlq': pl.Float64,
                'pub_rec_bankruptcies': pl.Int64,
                'total_bc_limit': pl.Float64}

In [12]:
# cast and cast earliest credit
cast_exec = [pl.col(column).cast(dtype, strict=False)
            for column, dtype in CAST_FEATURE.items()
            if column != "earliest_cr_line"]

cast_exec = cast_exec + [pl.col("earliest_cr_line").str.strptime(pl.Date, "%b-%Y", strict=False)]

df = df.with_columns(cast_exec)

In [13]:
df.head(5).collect()

shape: (5, 55)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ loa ┆ ter ┆ int ┆ gra ┆ emp ┆ hom ┆ ann ┆ ver ┆ pur ┆ add ┆ dti ┆ del ┆ ear ┆ fic ┆ inq ┆ mth ┆ pub ┆ rev ┆ tot ┆ ini ┆ col ┆ mth ┆ app ┆ tot ┆ tot ┆ ope ┆ ope ┆ mth ┆ tot ┆ il_ ┆ ope ┆ max ┆ all ┆ inq ┆ tot ┆ inq ┆ mo_ ┆ mo_ ┆ mo_ ┆ mo_ ┆ mor ┆ mth ┆ mth ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ pct ┆ pub ┆ tot ┆ loa ┆ iss ┆ def │
│ n_a ┆ m   ┆ _ra ┆ de  ┆ _le ┆ e_o ┆ ual ┆ ifi ┆ pos ┆ r_s ┆ --- ┆ inq ┆ lie ┆ o_r ┆ _la ┆ s_s ┆ _re ┆ ol_ ┆ al_ ┆ tia ┆ lec ┆ s_s ┆ lic ┆ _co ┆ _cu ┆ n_a ┆ n_i ┆ s_s ┆ al_ ┆ uti ┆ n_r ┆ _ba ┆ _ut ┆ _fi ┆ al_ ┆ _la ┆ sin ┆ sin ┆ sin ┆ sin ┆ t_a ┆ s_s ┆ s_s ┆ _ac ┆ _ac ┆ _il ┆ _tl ┆ _tl ┆ _tl ┆ _tl ┆ _re ┆ al_ ┆ n_s ┆ ue_ ┆ aul │
│ mnt ┆ --- ┆ te  ┆ --- ┆ ngt ┆ wne ┆ _in ┆ cat ┆ e   ┆ tat ┆ f64 ┆ _2y ┆ st_ ┆ ang ┆ st_ ┆ inc ┆ c   ┆ uti ┆ acc ┆ l_l ┆ tio ┆ inc ┆ ati ┆ ll_ ┆ r_b ┆ ct_ ┆ l_1 ┆ inc ┆ bal ┆ l   ┆ v_2 ┆ l_b ┆ il  ┆ --- ┆ cu_ ┆ st_ ┆ _ol ┆ _ol ┆ _rc ┆ _rc ┆ cc  ┆ inc ┆ inc ┆ cts ┆ tv_ ┆ _tl ┆ _12 ┆ _90 ┆ _op ┆ _nv ┆ c_b ┆ bc_ ┆ tat ┆ d   ┆ t   │
│ --- ┆ i64 ┆ --- ┆ cat ┆ h   ┆ rsh ┆ c   ┆ ion ┆ --- ┆ e   ┆     ┆ rs  ┆ cr_ ┆ e_l ┆ 6mt ┆ e_l ┆ --- ┆ l   ┆ --- ┆ ist ┆ ns_ ┆ e_l ┆ on_ ┆ amt ┆ al  ┆ il  ┆ 2m  ┆ e_r ┆ _il ┆ --- ┆ 4m  ┆ c   ┆ --- ┆ i64 ┆ tl  ┆ 12m ┆ d_i ┆ d_r ┆ nt_ ┆ nt_ ┆ --- ┆ e_r ┆ e_r ┆ _ev ┆ rev ┆ --- ┆ 0dp ┆ g_d ┆ _pa ┆ r_d ┆ ank ┆ lim ┆ us  ┆ --- ┆ --- │
│ i64 ┆     ┆ f64 ┆     ┆ --- ┆ ip  ┆ --- ┆ _st ┆ cat ┆ --- ┆     ┆ --- ┆ lin ┆ ow  ┆ hs  ┆ ast ┆ i64 ┆ --- ┆ i64 ┆ _st ┆ 12_ ┆ ast ┆ typ ┆ --- ┆ --- ┆ --- ┆ --- ┆ cnt ┆ --- ┆ f64 ┆ --- ┆ --- ┆ f64 ┆     ┆ --- ┆ --- ┆ l_a ┆ ev_ ┆ rev ┆ tl  ┆ i64 ┆ ece ┆ ece ┆ er_ ┆ _tl ┆ i64 ┆ d_2 ┆ pd_ ┆ st_ ┆ lq  ┆ rup ┆ it  ┆ --- ┆ dat ┆ i8  │
│     ┆     ┆     ┆     ┆ i64 ┆ --- ┆ f64 ┆ atu ┆     ┆ cat ┆     ┆ i64 ┆ e   ┆ --- ┆ --- ┆ _re ┆     ┆ f64 ┆     ┆ atu ┆ mth ┆ _ma ┆ e   ┆ f64 ┆ f64 ┆ i64 ┆ i64 ┆ _il ┆ f64 ┆     ┆ i64 ┆ f64 ┆     ┆     ┆ i64 ┆ i64 ┆ cct ┆ tl_ ┆ _tl ┆ --- ┆     ┆ nt_ ┆ nt_ ┆ 120 ┆ --- ┆     ┆ m   ┆ 24m ┆ 12m ┆ --- ┆ tci ┆ --- ┆ cat ┆ e   ┆     │
│     ┆     ┆     ┆     ┆     ┆ cat ┆     ┆ s   ┆     ┆     ┆     ┆     ┆ --- ┆ i64 ┆ i64 ┆ cor ┆     ┆     ┆     ┆ s   ┆ s_e ┆ jor ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ op  ┆ _op ┆ i64 ┆     ┆ bc  ┆ inq ┆ _pd ┆ i64 ┆     ┆ --- ┆ --- ┆ --- ┆ f64 ┆ es  ┆ f64 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ --- ┆ x_m ┆ _de ┆ cat ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ --- ┆ --- ┆     ┆     ┆ i64 ┆ i64 ┆ i64 ┆     ┆ --- ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cat ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ cat ┆ ed  ┆ rog ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆ i64 ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 120 ┆ 36  ┆ 7.9 ┆ A   ┆ nul ┆ OWN ┆ 420 ┆ Sou ┆ deb ┆ CA  ┆ 27. ┆ 0   ┆ 199 ┆ 715 ┆ 0   ┆ 80  ┆ 1   ┆ 37. ┆ 16  ┆ w   ┆ 0   ┆ nul ┆ Ind ┆ 0.0 ┆ 305 ┆ 2   ┆ 1   ┆ 8   ┆ 190 ┆ 73. ┆ 4   ┆ 711 ┆ 53. ┆ 1   ┆ 1   ┆ 2   ┆ 131 ┆ 255 ┆ 1   ┆ 1   ┆ 0   ┆ 14  ┆ 8   ┆ 0   ┆ 6   ┆ 7   ┆ 0   ┆ 0   ┆ 3   ┆ 100 ┆ 1   ┆ 155 ┆ Ful ┆ 201 ┆ 0   │
│ 00  ┆     ┆ 7   ┆     ┆ l   ┆     ┆ 00. ┆ rce ┆ t_c ┆     ┆ 74  ┆     ┆ 6-0 ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ l   ┆ ivi ┆     ┆ 02. ┆     ┆     ┆     ┆ 45. ┆ 0   ┆     ┆ 7.0 ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆     ┆ 00. ┆ ly  ┆ 7-0 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ Ver ┆ ons ┆     ┆     ┆     ┆ 6-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dua ┆     ┆ 0   ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ Pai ┆ 9-0 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ifi ┆ oli ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ 1   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 100 ┆ 36  ┆ 9.4 ┆ B   ┆ 3   ┆ MOR ┆ 550 ┆ Not ┆ deb ┆ OR  ┆ 18. ┆ 0   ┆ 200 ┆ 695 ┆ 0   ┆ 99  ┆ 1   ┆ 57. ┆ 10  ┆ w   ┆ 0   ┆ nul ┆ Ind ┆ 0.0 ┆ 340 ┆ 4   ┆ 1   ┆ 10  ┆ 209 ┆ 75. ┆ 0   ┆ 684 ┆ 68. ┆ 1   ┆ 1   ┆ 1   ┆ 144 ┆ 73  ┆ 49  ┆ 10  ┆ 2   ┆ 49  ┆ 8   ┆ 0   ┆ 2   ┆ 5   ┆ 0   ┆ 0   ┆ 1   ┆ 100 ┆ 1   ┆ 105 ┆ Ful ┆ 201 ┆ 0   │
│ 00  ┆     ┆ 4   ┆     ┆     ┆ TGA ┆ 00. ┆ Ver ┆ t_c ┆     ┆ 79  ┆     ┆ 5-0 ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆ l   ┆ ivi ┆     ┆ 607 ┆     ┆     ┆     ┆ 187 ┆ 0   ┆     ┆ 7.0 ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆     ┆ 00. ┆ ly  ┆ 7-0 ┆     │
│     ┆     ┆     ┆     ┆     ┆ GE  ┆ 0   ┆ ifi ┆ ons ┆     ┆     ┆     ┆ 9-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dua ┆     ┆ .0  ┆     ┆     ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ Pai ┆ 9-0 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ oli ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ 1   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 800 ┆ 36  ┆ 16. ┆ C   ┆ 0   ┆ MOR ┆ 120 ┆ Not ┆ deb ┆ NY  ┆ 20. ┆ 0   ┆ 199 ┆ 700 ┆ 1   ┆ nul ┆ 0   ┆ 92. ┆ 34  ┆ w   ┆ 0   ┆ nul ┆ Joi ┆ 0.0 ┆ 388 ┆ 3   ┆ 2   ┆ 6   ┆ 835 ┆ 85. ┆ 0   ┆ 0.0 ┆ 88. ┆ 1   ┆ 24  ┆ 2   ┆ 137 ┆ 276 ┆ 34  ┆ 6   ┆ 6   ┆ 152 ┆ 3   ┆ 0   ┆ 3   ┆ 19  ┆ 0   ┆ 0   ┆ 3   ┆ 97. ┆ 0   ┆ 0.0 ┆ Ful ┆ 201 ┆ 0   │
│ 0   ┆     ┆ 02  ┆     ┆     ┆ TGA ┆ 000 ┆ Ver ┆ t_c ┆     ┆ 36  ┆     ┆ 4-0 ┆     ┆     ┆ l   ┆     ┆ 3   ┆     ┆     ┆     ┆ l   ┆ nt  ┆     ┆ 595 ┆     ┆     ┆     ┆ 72. ┆ 0   ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆ ly  ┆ 7-0 ┆     │
│     ┆     ┆     ┆     ┆     ┆ GE  ┆ .0  ┆ ifi ┆ ons ┆     ┆     ┆     ┆ 9-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ App ┆     ┆ .0  ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pai ┆ 9-0 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ oli ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ 1   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 128 ┆ 36  ┆ 13. ┆ C   ┆ 5   ┆ REN ┆ 900 ┆ Not ┆ deb ┆ TX  ┆ 22. ┆ 0   ┆ 198 ┆ 660 ┆ 2   ┆ nul ┆ 0   ┆ 86. ┆ 23  ┆ w   ┆ 0   ┆ 94  ┆ Ind ┆ 0.0 ┆ 933 ┆ 3   ┆ 2   ┆ 6   ┆ 807 ┆ 91. ┆ 3   ┆ 377 ┆ 86. ┆ 0   ┆ 1   ┆ 2   ┆ 154 ┆ 345 ┆ 5   ┆ 5   ┆ 0   ┆ 5   ┆ 5   ┆ 0   ┆ 6   ┆ 15  ┆ nul ┆ 0   ┆ 3   ┆ 83. ┆ 0   ┆ 147 ┆ Ful ┆ 201 ┆ 0   │
│ 00  ┆     ┆ 59  ┆     ┆     ┆ T   ┆ 00. ┆ Ver ┆ t_c ┆     ┆ 63  ┆     ┆ 8-1 ┆     ┆     ┆ l   ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ ivi ┆     ┆ 75. ┆     ┆     ┆     ┆ 15. ┆ 0   ┆     ┆ 7.0 ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ 0   ┆     ┆ 50. ┆ ly  ┆ 7-0 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ ifi ┆ ons ┆     ┆     ┆     ┆ 2-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dua ┆     ┆ 0   ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ Pai ┆ 9-0 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ oli ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ 1   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 150 ┆ 36  ┆ 13. ┆ C   ┆ 4   ┆ MOR ┆ 180 ┆ Sou ┆ med ┆ TX  ┆ 38. ┆ 0   ┆ 197 ┆ 680 ┆ 0   ┆ nul ┆ 0   ┆ 66. ┆ 50  ┆ w   ┆ 0   ┆ nul ┆ Ind ┆ 0.0 ┆ 682 ┆ 4   ┆ 0   ┆ 13  ┆ 190 ┆ 79. ┆ 1   ┆ 221 ┆ 68. ┆ 2   ┆ 8   ┆ 0   ┆ 132 ┆ 489 ┆ 16  ┆ 13  ┆ 4   ┆ 16  ┆ 13  ┆ 0   ┆ 14  ┆ 17  ┆ 0   ┆ 0   ┆ 0   ┆ 100 ┆ 0   ┆ 116 ┆ Ful ┆ 201 ┆ 0   │
│ 00  ┆     ┆ 59  ┆     ┆     ┆ TGA ┆ 000 ┆ rce ┆ ica ┆     ┆ 07  ┆     ┆ 6-1 ┆     ┆     ┆ l   ┆     ┆ 6   ┆     ┆     ┆     ┆ l   ┆ ivi ┆     ┆ 000 ┆     ┆     ┆     ┆ 233 ┆ 0   ┆     ┆ 27. ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆     ┆ 700 ┆ ly  ┆ 7-0 ┆     │
│     ┆     ┆     ┆     ┆     ┆ GE  ┆ .0  ┆ Ver ┆ l   ┆     ┆     ┆     ┆ 2-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dua ┆     ┆ .0  ┆     ┆     ┆     ┆ .0  ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆ Pai ┆ 9-0 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ifi ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ 1   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

## 7.4 Missingness

In [22]:
def null_summary(df):
    total_rows = df.select(pl.len()).collect().item()

    null_summary = (
        df
        .select([
            pl.col(c).is_null().sum().alias(c)
            for c in df.collect_schema().names()
        ])
        .unpivot(
            variable_name="feature",
            value_name="null_count",
        )
        .with_columns(
            (pl.col("null_count") / total_rows * 100)
            .round(4)
            .alias("null_pct")
        )
        .filter(pl.col("null_count") > 0)
        .sort("null_count", descending=True)
        .collect()
    )

    print(f"Columns with nulls: {null_summary.height} / {len(df.collect_schema().names())}")
    print(null_summary)

In [ ]:
null_summary(df)

Columns with nulls: 22 / 55
shape: (22, 3)
┌─────────────────────────────┬────────────┬──────────┐
│ feature                     ┆ null_count ┆ null_pct │
│ ---                         ┆ ---        ┆ ---      │
│ str                         ┆ u32        ┆ f64      │
╞═════════════════════════════╪════════════╪══════════╡
│ mths_since_last_record      ┆ 819663     ┆ 82.4328  │
│ mths_since_last_major_derog ┆ 725489     ┆ 72.9618  │
│ emp_length                  ┆ 400674     ┆ 40.2954  │
│ il_util                     ┆ 139599     ┆ 14.0393  │
│ mths_since_recent_inq       ┆ 100068     ┆ 10.0638  │
│ num_tl_120dpd_2m            ┆ 41542      ┆ 4.1778   │
│ mths_since_rcnt_il          ┆ 28537      ┆ 2.8699   │
│ mo_sin_old_il_acct          ┆ 28486      ┆ 2.8648   │
│ mths_since_recent_bc        ┆ 11943      ┆ 1.2011   │
│ dti                         ┆ 1107       ┆ 0.1113   │
│ …                           ┆ …          ┆ …        │
│ total_cu_tl                 ┆ 57         ┆ 0.0057   │
│ inq_last_12m                ┆ 57         ┆ 0.0057   │
│ open_act_il                 ┆ 56         ┆ 0.0056   │
│ open_il_12m                 ┆ 56         ┆ 0.0056   │
│ total_bal_il                ┆ 56         ┆ 0.0056   │
│ open_rv_24m                 ┆ 56         ┆ 0.0056   │
│ max_bal_bc                  ┆ 56         ┆ 0.0056   │
│ inq_fi                      ┆ 56         ┆ 0.0056   │
│ inq_last_6mths              ┆ 1          ┆ 0.0001   │
│ pct_tl_nvr_dlq              ┆ 1          ┆ 0.0001   │
└─────────────────────────────┴────────────┴──────────┘

### 7.4.1 Months Since Feature Related

In [16]:
FEATURE_MTHS_ENG_FILL = ["mths_since_recent_bc", "mths_since_recent_inq", "mths_since_rcnt_il"]
FEATURE_MTHS_ENG_NULL = ["mths_since_recent_inq", "mths_since_last_record", "mths_since_last_major_derog"]

In [17]:
# mths imputation
df = (df
            .with_columns([
                pl.col(col).is_null().cast(pl.Int8).alias(f"{col}_null")
                for col in FEATURE_MTHS_ENG_NULL
            ])
            .with_columns([
                pl.col(col).fill_null(0)
                for col in FEATURE_MTHS_ENG_FILL
            ])
            .select(pl.exclude(FEATURE_MTHS_ENG_NULL))
)

In [18]:
df.head().collect()

shape: (5, 55)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ loa ┆ ter ┆ int ┆ gra ┆ emp ┆ hom ┆ ann ┆ ver ┆ pur ┆ add ┆ dti ┆ del ┆ ear ┆ fic ┆ inq ┆ pub ┆ rev ┆ tot ┆ ini ┆ col ┆ app ┆ tot ┆ tot ┆ ope ┆ ope ┆ mth ┆ tot ┆ il_ ┆ ope ┆ max ┆ all ┆ inq ┆ tot ┆ inq ┆ mo_ ┆ mo_ ┆ mo_ ┆ mo_ ┆ mor ┆ mth ┆ num ┆ num ┆ num ┆ num ┆ num ┆ num ┆ pct ┆ pub ┆ tot ┆ loa ┆ iss ┆ def ┆ mth ┆ mth ┆ mth │
│ n_a ┆ m   ┆ _ra ┆ de  ┆ _le ┆ e_o ┆ ual ┆ ifi ┆ pos ┆ r_s ┆ --- ┆ inq ┆ lie ┆ o_r ┆ _la ┆ _re ┆ ol_ ┆ al_ ┆ tia ┆ lec ┆ lic ┆ _co ┆ _cu ┆ n_a ┆ n_i ┆ s_s ┆ al_ ┆ uti ┆ n_r ┆ _ba ┆ _ut ┆ _fi ┆ al_ ┆ _la ┆ sin ┆ sin ┆ sin ┆ sin ┆ t_a ┆ s_s ┆ _ac ┆ _ac ┆ _il ┆ _tl ┆ _tl ┆ _tl ┆ _tl ┆ _re ┆ al_ ┆ n_s ┆ ue_ ┆ aul ┆ s_s ┆ s_s ┆ s_s │
│ mnt ┆ --- ┆ te  ┆ --- ┆ ngt ┆ wne ┆ _in ┆ cat ┆ e   ┆ tat ┆ f64 ┆ _2y ┆ st_ ┆ ang ┆ st_ ┆ c   ┆ uti ┆ acc ┆ l_l ┆ tio ┆ ati ┆ ll_ ┆ r_b ┆ ct_ ┆ l_1 ┆ inc ┆ bal ┆ l   ┆ v_2 ┆ l_b ┆ il  ┆ --- ┆ cu_ ┆ st_ ┆ _ol ┆ _ol ┆ _rc ┆ _rc ┆ cc  ┆ inc ┆ cts ┆ tv_ ┆ _tl ┆ _12 ┆ _90 ┆ _op ┆ _nv ┆ c_b ┆ bc_ ┆ tat ┆ d   ┆ t   ┆ inc ┆ inc ┆ inc │
│ --- ┆ i64 ┆ --- ┆ cat ┆ h   ┆ rsh ┆ c   ┆ ion ┆ --- ┆ e   ┆     ┆ rs  ┆ cr_ ┆ e_l ┆ 6mt ┆ --- ┆ l   ┆ --- ┆ ist ┆ ns_ ┆ on_ ┆ amt ┆ al  ┆ il  ┆ 2m  ┆ e_r ┆ _il ┆ --- ┆ 4m  ┆ c   ┆ --- ┆ i64 ┆ tl  ┆ 12m ┆ d_i ┆ d_r ┆ nt_ ┆ nt_ ┆ --- ┆ e_r ┆ _ev ┆ rev ┆ --- ┆ 0dp ┆ g_d ┆ _pa ┆ r_d ┆ ank ┆ lim ┆ us  ┆ --- ┆ --- ┆ e_r ┆ e_l ┆ e_l │
│ i64 ┆     ┆ f64 ┆     ┆ --- ┆ ip  ┆ --- ┆ _st ┆ cat ┆ --- ┆     ┆ --- ┆ lin ┆ ow  ┆ hs  ┆ i64 ┆ --- ┆ i64 ┆ _st ┆ 12_ ┆ typ ┆ --- ┆ --- ┆ --- ┆ --- ┆ cnt ┆ --- ┆ f64 ┆ --- ┆ --- ┆ f64 ┆     ┆ --- ┆ --- ┆ l_a ┆ ev_ ┆ rev ┆ tl  ┆ i64 ┆ ece ┆ er_ ┆ _tl ┆ i64 ┆ d_2 ┆ pd_ ┆ st_ ┆ lq  ┆ rup ┆ it  ┆ --- ┆ dat ┆ i8  ┆ ece ┆ ast ┆ ast │
│     ┆     ┆     ┆     ┆ i64 ┆ --- ┆ f64 ┆ atu ┆     ┆ cat ┆     ┆ i64 ┆ e   ┆ --- ┆ --- ┆     ┆ f64 ┆     ┆ atu ┆ mth ┆ e   ┆ f64 ┆ f64 ┆ i64 ┆ i64 ┆ _il ┆ f64 ┆     ┆ i64 ┆ f64 ┆     ┆     ┆ i64 ┆ i64 ┆ cct ┆ tl_ ┆ _tl ┆ --- ┆     ┆ nt_ ┆ 120 ┆ --- ┆     ┆ m   ┆ 24m ┆ 12m ┆ --- ┆ tci ┆ --- ┆ cat ┆ e   ┆     ┆ nt_ ┆ _re ┆ _ma │
│     ┆     ┆     ┆     ┆     ┆ cat ┆     ┆ s   ┆     ┆     ┆     ┆     ┆ --- ┆ i64 ┆ i64 ┆     ┆     ┆     ┆ s   ┆ s_e ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ op  ┆ _op ┆ i64 ┆     ┆ bc  ┆ _pd ┆ i64 ┆     ┆ --- ┆ --- ┆ --- ┆ f64 ┆ es  ┆ f64 ┆     ┆     ┆     ┆ inq ┆ cor ┆ jor │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ x_m ┆ cat ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ i64 ┆ i64 ┆ i64 ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ _nu ┆ d_n ┆ _de │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cat ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆ cat ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆ ll  ┆ ull ┆ rog │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ _nu │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i8  ┆ i8  ┆ ll  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i8  │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 120 ┆ 36  ┆ 7.9 ┆ A   ┆ nul ┆ OWN ┆ 420 ┆ Sou ┆ deb ┆ CA  ┆ 27. ┆ 0   ┆ 199 ┆ 715 ┆ 0   ┆ 1   ┆ 37. ┆ 16  ┆ w   ┆ 0   ┆ Ind ┆ 0.0 ┆ 305 ┆ 2   ┆ 1   ┆ 8   ┆ 190 ┆ 73. ┆ 4   ┆ 711 ┆ 53. ┆ 1   ┆ 1   ┆ 2   ┆ 131 ┆ 255 ┆ 1   ┆ 1   ┆ 0   ┆ 14  ┆ 0   ┆ 6   ┆ 7   ┆ 0   ┆ 0   ┆ 3   ┆ 100 ┆ 1   ┆ 155 ┆ Ful ┆ 201 ┆ 0   ┆ 0   ┆ 0   ┆ 1   │
│ 00  ┆     ┆ 7   ┆     ┆ l   ┆     ┆ 00. ┆ rce ┆ t_c ┆     ┆ 74  ┆     ┆ 6-0 ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ ivi ┆     ┆ 02. ┆     ┆     ┆     ┆ 45. ┆ 0   ┆     ┆ 7.0 ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆     ┆ 00. ┆ ly  ┆ 7-0 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ Ver ┆ ons ┆     ┆     ┆     ┆ 6-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dua ┆     ┆ 0   ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ Pai ┆ 9-0 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ifi ┆ oli ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ 1   ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 100 ┆ 36  ┆ 9.4 ┆ B   ┆ 3   ┆ MOR ┆ 550 ┆ Not ┆ deb ┆ OR  ┆ 18. ┆ 0   ┆ 200 ┆ 695 ┆ 0   ┆ 1   ┆ 57. ┆ 10  ┆ w   ┆ 0   ┆ Ind ┆ 0.0 ┆ 340 ┆ 4   ┆ 1   ┆ 10  ┆ 209 ┆ 75. ┆ 0   ┆ 684 ┆ 68. ┆ 1   ┆ 1   ┆ 1   ┆ 144 ┆ 73  ┆ 49  ┆ 10  ┆ 2   ┆ 49  ┆ 0   ┆ 2   ┆ 5   ┆ 0   ┆ 0   ┆ 1   ┆ 100 ┆ 1   ┆ 105 ┆ Ful ┆ 201 ┆ 0   ┆ 0   ┆ 0   ┆ 1   │
│ 00  ┆     ┆ 4   ┆     ┆     ┆ TGA ┆ 00. ┆ Ver ┆ t_c ┆     ┆ 79  ┆     ┆ 5-0 ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆ ivi ┆     ┆ 607 ┆     ┆     ┆     ┆ 187 ┆ 0   ┆     ┆ 7.0 ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆     ┆ 00. ┆ ly  ┆ 7-0 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ GE  ┆ 0   ┆ ifi ┆ ons ┆     ┆     ┆     ┆ 9-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dua ┆     ┆ .0  ┆     ┆     ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ Pai ┆ 9-0 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ oli ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ 1   ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 800 ┆ 36  ┆ 16. ┆ C   ┆ 0   ┆ MOR ┆ 120 ┆ Not ┆ deb ┆ NY  ┆ 20. ┆ 0   ┆ 199 ┆ 700 ┆ 1   ┆ 0   ┆ 92. ┆ 34  ┆ w   ┆ 0   ┆ Joi ┆ 0.0 ┆ 388 ┆ 3   ┆ 2   ┆ 6   ┆ 835 ┆ 85. ┆ 0   ┆ 0.0 ┆ 88. ┆ 1   ┆ 24  ┆ 2   ┆ 137 ┆ 276 ┆ 34  ┆ 6   ┆ 6   ┆ 152 ┆ 0   ┆ 3   ┆ 19  ┆ 0   ┆ 0   ┆ 3   ┆ 97. ┆ 0   ┆ 0.0 ┆ Ful ┆ 201 ┆ 0   ┆ 0   ┆ 1   ┆ 1   │
│ 0   ┆     ┆ 02  ┆     ┆     ┆ TGA ┆ 000 ┆ Ver ┆ t_c ┆     ┆ 36  ┆     ┆ 4-0 ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆ nt  ┆     ┆ 595 ┆     ┆     ┆     ┆ 72. ┆ 0   ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆ ly  ┆ 7-0 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ GE  ┆ .0  ┆ ifi ┆ ons ┆     ┆     ┆     ┆ 9-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ App ┆     ┆ .0  ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pai ┆ 9-0 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ oli ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ 1   ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 128 ┆ 36  ┆ 13. ┆ C   ┆ 5   ┆ REN ┆ 900 ┆ Not ┆ deb ┆ TX  ┆ 22. ┆ 0   ┆ 198 ┆ 660 ┆ 2   ┆ 0   ┆ 86. ┆ 23  ┆ w   ┆ 0   ┆ Ind ┆ 0.0 ┆ 933 ┆ 3   ┆ 2   ┆ 6   ┆ 807 ┆ 91. ┆ 3   ┆ 377 ┆ 86. ┆ 0   ┆ 1   ┆ 2   ┆ 154 ┆ 345 ┆ 5   ┆ 5   ┆ 0   ┆ 5   ┆ 0   ┆ 6   ┆ 15  ┆ nul ┆ 0   ┆ 3   ┆ 83. ┆ 0   ┆ 147 ┆ Ful ┆ 201 ┆ 0   ┆ 0   ┆ 1   ┆ 0   │
│ 00  ┆     ┆ 59  ┆     ┆     ┆ T   ┆ 00. ┆ Ver ┆ t_c ┆     ┆ 63  ┆     ┆ 8-1 ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ ivi ┆     ┆ 75. ┆     ┆     ┆     ┆ 15. ┆ 0   ┆     ┆ 7.0 ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ 0   ┆     ┆ 50. ┆ ly  ┆ 7-0 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ ifi ┆ ons ┆     ┆     ┆     ┆ 2-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dua ┆     ┆ 0   ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ Pai ┆ 9-0 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ oli ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ 1   ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 150 ┆ 36  ┆ 13. ┆ C   ┆ 4   ┆ MOR ┆ 180 ┆ Sou ┆ med ┆ TX  ┆ 38. ┆ 0   ┆ 197 ┆ 680 ┆ 0   ┆ 0   ┆ 66. ┆ 50  ┆ w   ┆ 0   ┆ Ind ┆ 0.0 ┆ 682 ┆ 4   ┆ 0   ┆ 13  ┆ 190 ┆ 79. ┆ 1   ┆ 221 ┆ 68. ┆ 2   ┆ 8   ┆ 0   ┆ 132 ┆ 489 ┆ 16  ┆ 13  ┆ 4   ┆ 16  ┆ 0   ┆ 14  ┆ 17  ┆ 0   ┆ 0   ┆ 0   ┆ 100 ┆ 0   ┆ 116 ┆ Ful ┆ 201 ┆ 0   ┆ 0   ┆ 1   ┆ 1   │
│ 00  ┆     ┆ 59  ┆     ┆     ┆ TGA ┆ 000 ┆ rce ┆ ica ┆     ┆ 07  ┆     ┆ 6-1 ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆ ivi ┆     ┆ 000 ┆     ┆     ┆     ┆ 233 ┆ 0   ┆     ┆ 27. ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆     ┆ 700 ┆ ly  ┆ 7-0 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ GE  ┆ .0  ┆ Ver ┆ l   ┆     ┆     ┆     ┆ 2-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dua ┆     ┆ .0  ┆     ┆     ┆     ┆ .0  ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆ Pai ┆ 9-0 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ifi ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ 1   ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [23]:
null_summary(df)

Columns with nulls: 17 / 55
shape: (17, 3)
┌────────────────────┬────────────┬──────────┐
│ feature            ┆ null_count ┆ null_pct │
│ ---                ┆ ---        ┆ ---      │
│ str                ┆ u32        ┆ f64      │
╞════════════════════╪════════════╪══════════╡
│ emp_length         ┆ 400674     ┆ 40.2954  │
│ il_util            ┆ 139599     ┆ 14.0393  │
│ num_tl_120dpd_2m   ┆ 41542      ┆ 4.1778   │
│ mo_sin_old_il_acct ┆ 28486      ┆ 2.8648   │
│ dti                ┆ 1107       ┆ 0.1113   │
│ revol_util         ┆ 943        ┆ 0.0948   │
│ all_util           ┆ 195        ┆ 0.0196   │
│ total_cu_tl        ┆ 57         ┆ 0.0057   │
│ inq_last_12m       ┆ 57         ┆ 0.0057   │
│ open_act_il        ┆ 56         ┆ 0.0056   │
│ open_il_12m        ┆ 56         ┆ 0.0056   │
│ total_bal_il       ┆ 56         ┆ 0.0056   │
│ open_rv_24m        ┆ 56         ┆ 0.0056   │
│ max_bal_bc         ┆ 56         ┆ 0.0056   │
│ inq_fi             ┆ 56         ┆ 0.0056   │
│ inq_last_6mths     ┆ 1          ┆ 0.0001   │
│ pct_tl_nvr_dlq     ┆ 1          ┆ 0.0001   │
└────────────────────┴────────────┴──────────┘

### 7.4.2 Employment

## 7.5 Transformation

In [20]:
# df =  (df.with_columns(
#     ((pl.col("issue_d") - pl.col("earliest_cr_line")).dt.total_days() // 30)
#     .alias("cr_age_mths")))