In [1]:
# import libraries
import polars as pl
from datetime import date
from tqdm.notebook import tqdm
import plotly.express as px

pl.Config.set_tbl_rows(20)
pl.Config.set_tbl_cols(-1)
pl.Config.set_fmt_str_lengths(100)
pl.Config.set_tbl_width_chars(200)

# data path
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent.parent))

from src.config.paths import RAW_DIR, INTERIM_DIR, PROCESSED_DIR, DOCS_DIR

In [2]:
# load cleaned data
df = pl.scan_parquet(INTERIM_DIR / "cleaned.parquet")

# 8. Data Model Preparation

**Main Objective**

Transform the selected origination-time features into a model-ready representation while preserving predictive information, interpretability, and leakage control.

## 8.1 One Hot Encoding

In [3]:
CAT_FEATURES = [i for i,d in df.collect_schema().items() if not d.is_numeric()]
CAT_FEATURES.remove("issue_d")

CAT_FEATURE_VALUES = {}

for feature in CAT_FEATURES:
    values = (
        df
        .select(
            pl.col(feature)
            .drop_nulls()
            .cast(pl.String)
            .unique()
            .sort()
        )
        .collect()
        .to_series()
        .to_list()
    )

    CAT_FEATURE_VALUES[feature] = values

In [4]:
print(CAT_FEATURE_VALUES)

{'grade': ['A', 'B', 'C', 'D', 'E', 'F', 'G'], 'initial_list_status': ['f', 'w'], 'application_type': ['Individual', 'Joint App'], 'purpose': ['car', 'credit_card', 'debt_consolidation', 'educational', 'home_improvement', 'house', 'major_purchase', 'medical', 'moving', 'other', 'renewable_energy', 'small_business', 'vacation', 'wedding'], 'home_ownership': ['ANY', 'MORTGAGE', 'NONE', 'OWN', 'RENT'], 'verification_status': ['Not Verified', 'Source Verified', 'Verified'], 'addr_state': ['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY']}

In [5]:
from src.config.categories import OHE_CATEGORIES

In [6]:
def one_hot_encode(df: pl.DataFrame | pl.LazyFrame,):
    expressions = []

    for feature, categories in OHE_CATEGORIES.items():

        for category in categories:

            encoded_name = f"{feature}_{category}"

            expressions.append(
                (
                    pl.col(feature).cast(pl.String)
                    == pl.lit(category)
                )
                .fill_null(False)
                .cast(pl.UInt8)
                .alias(encoded_name)
            )

    return (df
            .with_columns(expressions)
            .select(pl.exclude(OHE_CATEGORIES.keys())))

In [7]:
df = one_hot_encode(df)

In [8]:
df.head().sort("issue_d").collect()

shape: (5, 131)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ loa ┆ ter ┆ int ┆ emp ┆ ann ┆ fic ┆ mo_ ┆ mo_ ┆ mo_ ┆ mo_ ┆ num ┆ dti ┆ tot ┆ ope ┆ ope ┆ ope ┆ all ┆ tot ┆ pct ┆ mor ┆ tot ┆ num ┆ rev ┆ max ┆ mth ┆ tot ┆ mth ┆ tot ┆ il_ ┆ inq ┆ inq ┆ inq ┆ del ┆ num ┆ num ┆ num ┆ col ┆ pub ┆ pub ┆ tot ┆ num ┆ mth ┆ mth ┆ mth ┆ emp ┆ cr_ ┆ def ┆ iss ┆ gra ┆ gra ┆ gra ┆ gra ┆ gra ┆ gra ┆ gra ┆ ini ┆ ini ┆ app ┆ app ┆ pur ┆ pur ┆ pur ┆ pur ┆ pur ┆ pur ┆ pur ┆ pur ┆ pur ┆ pur ┆ pur ┆ pur ┆ pur ┆ pur ┆ hom ┆ hom ┆ hom ┆ hom ┆ hom ┆ ver ┆ ver ┆ ver ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add │
│ n_a ┆ m   ┆ _ra ┆ _le ┆ ual ┆ o_r ┆ sin ┆ sin ┆ sin ┆ sin ┆ _tl ┆ --- ┆ al_ ┆ n_a ┆ n_i ┆ n_r ┆ _ut ┆ al_ ┆ _tl ┆ t_a ┆ _cu ┆ _ac ┆ ol_ ┆ _ba ┆ s_s ┆ al_ ┆ s_s ┆ al_ ┆ uti ┆ _la ┆ _fi ┆ _la ┆ inq ┆ _ac ┆ _tl ┆ _tl ┆ lec ┆ _re ┆ _re ┆ _co ┆ _il ┆ s_s ┆ s_s ┆ s_s ┆ _le ┆ age ┆ aul ┆ ue_ ┆ de_ ┆ de_ ┆ de_ ┆ de_ ┆ de_ ┆ de_ ┆ de_ ┆ tia ┆ tia ┆ lic ┆ lic ┆ pos ┆ pos ┆ pos ┆ pos ┆ pos ┆ pos ┆ pos ┆ pos ┆ pos ┆ pos ┆ pos ┆ pos ┆ pos ┆ pos ┆ e_o ┆ e_o ┆ e_o ┆ e_o ┆ e_o ┆ ifi ┆ ifi ┆ ifi ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s │
│ mnt ┆ --- ┆ te  ┆ ngt ┆ _in ┆ ang ┆ _ol ┆ _ol ┆ _rc ┆ _rc ┆ _op ┆ f64 ┆ acc ┆ ct_ ┆ l_1 ┆ v_2 ┆ il  ┆ cu_ ┆ _nv ┆ cc  ┆ r_b ┆ tv_ ┆ uti ┆ l_b ┆ inc ┆ bc_ ┆ inc ┆ bal ┆ l   ┆ st_ ┆ --- ┆ st_ ┆ _2y ┆ cts ┆ _12 ┆ _90 ┆ tio ┆ c   ┆ c_b ┆ ll_ ┆ _tl ┆ inc ┆ inc ┆ inc ┆ ngt ┆ _mt ┆ t   ┆ d   ┆ A   ┆ B   ┆ C   ┆ D   ┆ E   ┆ F   ┆ G   ┆ l_l ┆ l_l ┆ ati ┆ ati ┆ e_c ┆ e_c ┆ e_d ┆ e_e ┆ e_h ┆ e_h ┆ e_m ┆ e_m ┆ e_m ┆ e_o ┆ e_r ┆ e_s ┆ e_v ┆ e_w ┆ wne ┆ wne ┆ wne ┆ wne ┆ wne ┆ cat ┆ cat ┆ cat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat │
│ --- ┆ i64 ┆ --- ┆ h   ┆ c   ┆ e_l ┆ d_i ┆ d_r ┆ nt_ ┆ nt_ ┆ _pa ┆     ┆ --- ┆ il  ┆ 2m  ┆ 4m  ┆ --- ┆ tl  ┆ r_d ┆ --- ┆ al  ┆ rev ┆ l   ┆ c   ┆ e_r ┆ lim ┆ e_r ┆ _il ┆ --- ┆ 6mt ┆ f64 ┆ 12m ┆ rs  ┆ _ev ┆ 0dp ┆ g_d ┆ ns_ ┆ --- ┆ ank ┆ amt ┆ --- ┆ e_r ┆ e_l ┆ e_l ┆ h_n ┆ hs  ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ist ┆ ist ┆ on_ ┆ on_ ┆ ar  ┆ red ┆ ebt ┆ duc ┆ ome ┆ ous ┆ ajo ┆ edi ┆ ovi ┆ the ┆ ene ┆ mal ┆ aca ┆ edd ┆ rsh ┆ rsh ┆ rsh ┆ rsh ┆ rsh ┆ ion ┆ ion ┆ ion ┆ e_A ┆ e_A ┆ e_A ┆ e_A ┆ e_C ┆ e_C ┆ e_C ┆ e_D ┆ e_D ┆ e_F ┆ e_G ┆ e_H ┆ e_I ┆ e_I ┆ e_I ┆ e_K ┆ e_K ┆ e_L ┆ e_M ┆ e_M ┆ e_M ┆ e_M ┆ e_M ┆ e_M ┆ e_M ┆ e_M ┆ e_N ┆ e_N ┆ e_N ┆ e_N ┆ e_N ┆ e_N ┆ e_N ┆ e_N ┆ e_O ┆ e_O ┆ e_O ┆ e_P ┆ e_R ┆ e_S ┆ e_S ┆ e_T ┆ e_T ┆ e_U ┆ e_V ┆ e_V ┆ e_W ┆ e_W ┆ e_W ┆ e_W │
│ i64 ┆     ┆ f64 ┆ --- ┆ --- ┆ ow  ┆ l_a ┆ ev_ ┆ rev ┆ tl  ┆ st_ ┆     ┆ i64 ┆ --- ┆ --- ┆ --- ┆ f64 ┆ --- ┆ lq  ┆ i64 ┆ --- ┆ _tl ┆ --- ┆ --- ┆ ece ┆ it  ┆ cnt ┆ --- ┆ f64 ┆ hs  ┆     ┆ --- ┆ --- ┆ er_ ┆ d_2 ┆ pd_ ┆ 12_ ┆ i64 ┆ rup ┆ --- ┆ i64 ┆ ece ┆ ast ┆ ast ┆ ull ┆ --- ┆ i8  ┆ dat ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ _st ┆ _st ┆ typ ┆ typ ┆ --- ┆ it_ ┆ _co ┆ ati ┆ _im ┆ e   ┆ r_p ┆ cal ┆ ng  ┆ r   ┆ wab ┆ l_b ┆ tio ┆ ing ┆ ip_ ┆ ip_ ┆ ip_ ┆ ip_ ┆ ip_ ┆ _st ┆ _st ┆ _st ┆ K   ┆ L   ┆ R   ┆ Z   ┆ A   ┆ O   ┆ T   ┆ C   ┆ E   ┆ L   ┆ A   ┆ I   ┆ D   ┆ L   ┆ N   ┆ S   ┆ Y   ┆ A   ┆ A   ┆ D   ┆ E   ┆ I   ┆ N   ┆ O   ┆ S   ┆ T   ┆ C   ┆ D   ┆ E   ┆ H   ┆ J   ┆ M   ┆ V   ┆ Y   ┆ H   ┆ K   ┆ R   ┆ A   ┆ I   ┆ C   ┆ D   ┆ N   ┆ X   ┆ T   ┆ A   ┆ T   ┆ A   ┆ I   ┆ V   ┆ Y   │
│     ┆     ┆     ┆ i64 ┆ f64 ┆ --- ┆ cct ┆ tl_ ┆ _tl ┆ --- ┆ 12m ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆     ┆ f64 ┆ --- ┆     ┆ f64 ┆ --- ┆ f64 ┆ f64 ┆ nt_ ┆ --- ┆ _il ┆ f64 ┆     ┆ --- ┆     ┆ f64 ┆ i64 ┆ 120 ┆ m   ┆ 24m ┆ mth ┆     ┆ tci ┆ f64 ┆     ┆ nt_ ┆ _re ┆ _ma ┆ --- ┆ i64 ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ atu ┆ e_I ┆ e_J ┆ u8  ┆ car ┆ nso ┆ ona ┆ pro ┆ --- ┆ urc ┆ --- ┆ --- ┆ --- ┆ le_ ┆ usi ┆ n   ┆ --- ┆ ANY ┆ MOR ┆ NON ┆ OWN ┆ REN ┆ atu ┆ atu ┆ atu ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- │
│     ┆     ┆     ┆     ┆     ┆ i64 ┆ --- ┆ op  ┆ _op ┆ i64 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆ i64 ┆     ┆     ┆ bc  ┆ f64 ┆ --- ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆ _pd ┆ --- ┆ --- ┆ s_e ┆     ┆ es  ┆     ┆     ┆ inq ┆ cor ┆ jor ┆ i8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_f ┆ s_w ┆ ndi ┆ oin ┆     ┆ d   ┆ lid ┆ l   ┆ vem ┆ u8  ┆ has ┆ u8  ┆ u8  ┆ u8  ┆ ene ┆ nes ┆ --- ┆ u8  ┆ --- ┆ TGA ┆ E   ┆ --- ┆ T   ┆ s_N ┆ s_S ┆ s_V ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  │
│     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ f64 ┆ i64 ┆ x_m ┆     ┆ --- ┆     ┆     ┆ _nu ┆ d_n ┆ _de ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ vid ┆ t   ┆     ┆ --- ┆ ati ┆ --- ┆ ent ┆     ┆ e   ┆     ┆     ┆     ┆ rgy ┆ s   ┆ u8  ┆     ┆ u8  ┆ GE  ┆ --- ┆ u8  ┆ --- ┆ ot  ┆ our ┆ eri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆ ed  ┆     ┆ i64 ┆     ┆     ┆ ll  ┆ ull ┆ rog ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ u8  ┆ ual ┆ App ┆     ┆ u8  ┆ on  ┆ u8  ┆ --- ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆ --- ┆ u8  ┆     ┆ u8  ┆ Ver ┆ ce  ┆ fie ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ _nu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ --- ┆     ┆ u8  ┆     ┆ u8  ┆     ┆     ┆     ┆ u8  ┆ u8  ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆ ifi ┆ Ver ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆ i8  ┆ i8  ┆ ll  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ u8  ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ ifi ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ ed  ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 120 ┆ 36  ┆ 7.9 ┆ 0   ┆ 420 ┆ 715 ┆ 131 ┆ 255 ┆ 1   ┆ 1   ┆ 3   ┆ 27. ┆ 16  ┆ 2.0 ┆ 1.0 ┆ 4.0 ┆ 53. ┆ 1.0 ┆ 100 ┆ 0   ┆ 305 ┆ 6   ┆ 37. ┆ 711 ┆ 14  ┆ 155 ┆ 8   ┆ 190 ┆ 73. ┆ 0.0 ┆ 1.0 ┆ 2.0 ┆ 0   ┆ 0   ┆ 0.0 ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 0.0 ┆ 7   ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 258 ┆ 0   ┆ 201 ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ 00  ┆     ┆ 7   ┆     ┆ 00. ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆ 74  ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ .0  ┆     ┆ 02. ┆     ┆ 0   ┆ 7.0 ┆     ┆ 00. ┆     ┆ 45. ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 100 ┆ 36  ┆ 9.4 ┆ 3   ┆ 550 ┆ 695 ┆ 144 ┆ 73  ┆ 49  ┆ 10  ┆ 1   ┆ 18. ┆ 10  ┆ 4.0 ┆ 1.0 ┆ 0.0 ┆ 68. ┆ 1.0 ┆ 100 ┆ 2   ┆ 340 ┆ 2   ┆ 57. ┆ 684 ┆ 49  ┆ 105 ┆ 10  ┆ 209 ┆ 75. ┆ 0.0 ┆ 1.0 ┆ 1.0 ┆ 0   ┆ 0   ┆ 0.0 ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 0.0 ┆ 5   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 146 ┆ 0   ┆ 201 ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ 00  ┆     ┆ 4   ┆     ┆ 00. ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆ 79  ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ .0  ┆     ┆ 607 ┆     ┆ 5   ┆ 7.0 ┆     ┆ 00. ┆     ┆ 187 ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 800 ┆ 36  ┆ 16. ┆ 0   ┆ 120 ┆ 700 ┆ 137 ┆ 276 ┆ 34  ┆ 6   ┆ 3   ┆ 20. ┆ 34  ┆ 3.0 ┆ 2.0 ┆ 0.0 ┆ 88. ┆ 24. ┆ 97. ┆ 6   ┆ 388 ┆ 3   ┆ 92. ┆ 0.0 ┆ 152 ┆ 0.0 ┆ 6   ┆ 835 ┆ 85. ┆ 1.0 ┆ 1.0 ┆ 2.0 ┆ 0   ┆ 0   ┆ 0.0 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0.0 ┆ 19  ┆ 0   ┆ 1   ┆ 1   ┆ 0   ┆ 280 ┆ 0   ┆ 201 ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   │

## 8.2 Temporal Split

In [9]:
total_rows = df.select(pl.len()).collect().item()

issue_d_cumsum = (df
                    .select("issue_d")
                    .group_by("issue_d")
                    .agg(pl.len().alias("count"))
                    .sort("issue_d")
                    .with_columns(
                        (pl.col("count") / total_rows * 100.0).cast(pl.Float64).round(2).alias("pct"),
                        (pl.col("count").cum_sum().alias("count_cumsum"))
                    )
                    .with_columns(
                        (pl.col("count_cumsum") / total_rows * 100.0).cast(pl.Float64).round(2).alias("pct_cumsum")
                    )
                    .collect())

In [10]:
import plotly.express as px
import pandas as pd

df_pd = issue_d_cumsum.to_pandas()

# Convert the first and last dates to strings with format YYYY-MM-DD
first_date_str = df_pd['issue_d'].min().strftime('%Y-%m-%d')
last_date_str = df_pd['issue_d'].max().strftime('%Y-%m-%d')

fig = px.line(
    df_pd,
    x="issue_d",
    y="pct_cumsum",
    markers=True,
    title="Data Cumulative Split (85 / 10 / 5)",
    labels={
        "issue_d": "Vintage",
        "pct_cumsum": "Percentage",
    },
)

# 1. Highlight Train Area (Start to Jul 2018)
fig.add_vrect(
    x0=first_date_str, 
    x1="2018-07-01",
    fillcolor="green", 
    opacity=0.1, 
    layer="below", 
    line_width=0,
    annotation_text="Train (85%)", 
    annotation_position="top left"
)

# 2. Highlight Validation Area (Aug 2018 to Mar 2019)
fig.add_vrect(
    x0="2018-07-01", 
    x1="2019-03-01",
    fillcolor="orange", 
    opacity=0.1, 
    layer="below", 
    line_width=0,
    annotation_text="Val (10%)", 
    annotation_position="top left"
)

# 3. Highlight Test Area (Apr 2019 to End)
fig.add_vrect(
    x0="2019-03-01", 
    x1=last_date_str,
    fillcolor="red", 
    opacity=0.1, 
    layer="below", 
    line_width=0,
    annotation_text="Test (5%)", 
    annotation_position="top left"
)

fig.show()

In [12]:
from src.data.split import temporal_split, split_xy

df_train, df_val, df_test = temporal_split(df, val_start="2018-08-01", test_start="2019-04-01")

In [15]:
df_train.head().collect()

shape: (5, 131)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ loa ┆ ter ┆ int ┆ emp ┆ ann ┆ fic ┆ mo_ ┆ mo_ ┆ mo_ ┆ mo_ ┆ num ┆ dti ┆ tot ┆ ope ┆ ope ┆ ope ┆ all ┆ tot ┆ pct ┆ mor ┆ tot ┆ num ┆ rev ┆ max ┆ mth ┆ tot ┆ mth ┆ tot ┆ il_ ┆ inq ┆ inq ┆ inq ┆ del ┆ num ┆ num ┆ num ┆ col ┆ pub ┆ pub ┆ tot ┆ num ┆ mth ┆ mth ┆ mth ┆ emp ┆ cr_ ┆ def ┆ iss ┆ gra ┆ gra ┆ gra ┆ gra ┆ gra ┆ gra ┆ gra ┆ ini ┆ ini ┆ app ┆ app ┆ pur ┆ pur ┆ pur ┆ pur ┆ pur ┆ pur ┆ pur ┆ pur ┆ pur ┆ pur ┆ pur ┆ pur ┆ pur ┆ pur ┆ hom ┆ hom ┆ hom ┆ hom ┆ hom ┆ ver ┆ ver ┆ ver ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add ┆ add │
│ n_a ┆ m   ┆ _ra ┆ _le ┆ ual ┆ o_r ┆ sin ┆ sin ┆ sin ┆ sin ┆ _tl ┆ --- ┆ al_ ┆ n_a ┆ n_i ┆ n_r ┆ _ut ┆ al_ ┆ _tl ┆ t_a ┆ _cu ┆ _ac ┆ ol_ ┆ _ba ┆ s_s ┆ al_ ┆ s_s ┆ al_ ┆ uti ┆ _la ┆ _fi ┆ _la ┆ inq ┆ _ac ┆ _tl ┆ _tl ┆ lec ┆ _re ┆ _re ┆ _co ┆ _il ┆ s_s ┆ s_s ┆ s_s ┆ _le ┆ age ┆ aul ┆ ue_ ┆ de_ ┆ de_ ┆ de_ ┆ de_ ┆ de_ ┆ de_ ┆ de_ ┆ tia ┆ tia ┆ lic ┆ lic ┆ pos ┆ pos ┆ pos ┆ pos ┆ pos ┆ pos ┆ pos ┆ pos ┆ pos ┆ pos ┆ pos ┆ pos ┆ pos ┆ pos ┆ e_o ┆ e_o ┆ e_o ┆ e_o ┆ e_o ┆ ifi ┆ ifi ┆ ifi ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s ┆ r_s │
│ mnt ┆ --- ┆ te  ┆ ngt ┆ _in ┆ ang ┆ _ol ┆ _ol ┆ _rc ┆ _rc ┆ _op ┆ f64 ┆ acc ┆ ct_ ┆ l_1 ┆ v_2 ┆ il  ┆ cu_ ┆ _nv ┆ cc  ┆ r_b ┆ tv_ ┆ uti ┆ l_b ┆ inc ┆ bc_ ┆ inc ┆ bal ┆ l   ┆ st_ ┆ --- ┆ st_ ┆ _2y ┆ cts ┆ _12 ┆ _90 ┆ tio ┆ c   ┆ c_b ┆ ll_ ┆ _tl ┆ inc ┆ inc ┆ inc ┆ ngt ┆ _mt ┆ t   ┆ d   ┆ A   ┆ B   ┆ C   ┆ D   ┆ E   ┆ F   ┆ G   ┆ l_l ┆ l_l ┆ ati ┆ ati ┆ e_c ┆ e_c ┆ e_d ┆ e_e ┆ e_h ┆ e_h ┆ e_m ┆ e_m ┆ e_m ┆ e_o ┆ e_r ┆ e_s ┆ e_v ┆ e_w ┆ wne ┆ wne ┆ wne ┆ wne ┆ wne ┆ cat ┆ cat ┆ cat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat ┆ tat │
│ --- ┆ i64 ┆ --- ┆ h   ┆ c   ┆ e_l ┆ d_i ┆ d_r ┆ nt_ ┆ nt_ ┆ _pa ┆     ┆ --- ┆ il  ┆ 2m  ┆ 4m  ┆ --- ┆ tl  ┆ r_d ┆ --- ┆ al  ┆ rev ┆ l   ┆ c   ┆ e_r ┆ lim ┆ e_r ┆ _il ┆ --- ┆ 6mt ┆ f64 ┆ 12m ┆ rs  ┆ _ev ┆ 0dp ┆ g_d ┆ ns_ ┆ --- ┆ ank ┆ amt ┆ --- ┆ e_r ┆ e_l ┆ e_l ┆ h_n ┆ hs  ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ist ┆ ist ┆ on_ ┆ on_ ┆ ar  ┆ red ┆ ebt ┆ duc ┆ ome ┆ ous ┆ ajo ┆ edi ┆ ovi ┆ the ┆ ene ┆ mal ┆ aca ┆ edd ┆ rsh ┆ rsh ┆ rsh ┆ rsh ┆ rsh ┆ ion ┆ ion ┆ ion ┆ e_A ┆ e_A ┆ e_A ┆ e_A ┆ e_C ┆ e_C ┆ e_C ┆ e_D ┆ e_D ┆ e_F ┆ e_G ┆ e_H ┆ e_I ┆ e_I ┆ e_I ┆ e_K ┆ e_K ┆ e_L ┆ e_M ┆ e_M ┆ e_M ┆ e_M ┆ e_M ┆ e_M ┆ e_M ┆ e_M ┆ e_N ┆ e_N ┆ e_N ┆ e_N ┆ e_N ┆ e_N ┆ e_N ┆ e_N ┆ e_O ┆ e_O ┆ e_O ┆ e_P ┆ e_R ┆ e_S ┆ e_S ┆ e_T ┆ e_T ┆ e_U ┆ e_V ┆ e_V ┆ e_W ┆ e_W ┆ e_W ┆ e_W │
│ i64 ┆     ┆ f64 ┆ --- ┆ --- ┆ ow  ┆ l_a ┆ ev_ ┆ rev ┆ tl  ┆ st_ ┆     ┆ i64 ┆ --- ┆ --- ┆ --- ┆ f64 ┆ --- ┆ lq  ┆ i64 ┆ --- ┆ _tl ┆ --- ┆ --- ┆ ece ┆ it  ┆ cnt ┆ --- ┆ f64 ┆ hs  ┆     ┆ --- ┆ --- ┆ er_ ┆ d_2 ┆ pd_ ┆ 12_ ┆ i64 ┆ rup ┆ --- ┆ i64 ┆ ece ┆ ast ┆ ast ┆ ull ┆ --- ┆ i8  ┆ dat ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ _st ┆ _st ┆ typ ┆ typ ┆ --- ┆ it_ ┆ _co ┆ ati ┆ _im ┆ e   ┆ r_p ┆ cal ┆ ng  ┆ r   ┆ wab ┆ l_b ┆ tio ┆ ing ┆ ip_ ┆ ip_ ┆ ip_ ┆ ip_ ┆ ip_ ┆ _st ┆ _st ┆ _st ┆ K   ┆ L   ┆ R   ┆ Z   ┆ A   ┆ O   ┆ T   ┆ C   ┆ E   ┆ L   ┆ A   ┆ I   ┆ D   ┆ L   ┆ N   ┆ S   ┆ Y   ┆ A   ┆ A   ┆ D   ┆ E   ┆ I   ┆ N   ┆ O   ┆ S   ┆ T   ┆ C   ┆ D   ┆ E   ┆ H   ┆ J   ┆ M   ┆ V   ┆ Y   ┆ H   ┆ K   ┆ R   ┆ A   ┆ I   ┆ C   ┆ D   ┆ N   ┆ X   ┆ T   ┆ A   ┆ T   ┆ A   ┆ I   ┆ V   ┆ Y   │
│     ┆     ┆     ┆ i64 ┆ f64 ┆ --- ┆ cct ┆ tl_ ┆ _tl ┆ --- ┆ 12m ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆     ┆ f64 ┆ --- ┆     ┆ f64 ┆ --- ┆ f64 ┆ f64 ┆ nt_ ┆ --- ┆ _il ┆ f64 ┆     ┆ --- ┆     ┆ f64 ┆ i64 ┆ 120 ┆ m   ┆ 24m ┆ mth ┆     ┆ tci ┆ f64 ┆     ┆ nt_ ┆ _re ┆ _ma ┆ --- ┆ i64 ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ atu ┆ e_I ┆ e_J ┆ u8  ┆ car ┆ nso ┆ ona ┆ pro ┆ --- ┆ urc ┆ --- ┆ --- ┆ --- ┆ le_ ┆ usi ┆ n   ┆ --- ┆ ANY ┆ MOR ┆ NON ┆ OWN ┆ REN ┆ atu ┆ atu ┆ atu ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- │
│     ┆     ┆     ┆     ┆     ┆ i64 ┆ --- ┆ op  ┆ _op ┆ i64 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆ i64 ┆     ┆     ┆ bc  ┆ f64 ┆ --- ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆ _pd ┆ --- ┆ --- ┆ s_e ┆     ┆ es  ┆     ┆     ┆ inq ┆ cor ┆ jor ┆ i8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_f ┆ s_w ┆ ndi ┆ oin ┆     ┆ d   ┆ lid ┆ l   ┆ vem ┆ u8  ┆ has ┆ u8  ┆ u8  ┆ u8  ┆ ene ┆ nes ┆ --- ┆ u8  ┆ --- ┆ TGA ┆ E   ┆ --- ┆ T   ┆ s_N ┆ s_S ┆ s_V ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  │
│     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ f64 ┆ i64 ┆ x_m ┆     ┆ --- ┆     ┆     ┆ _nu ┆ d_n ┆ _de ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ vid ┆ t   ┆     ┆ --- ┆ ati ┆ --- ┆ ent ┆     ┆ e   ┆     ┆     ┆     ┆ rgy ┆ s   ┆ u8  ┆     ┆ u8  ┆ GE  ┆ --- ┆ u8  ┆ --- ┆ ot  ┆ our ┆ eri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆ ed  ┆     ┆ i64 ┆     ┆     ┆ ll  ┆ ull ┆ rog ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ u8  ┆ ual ┆ App ┆     ┆ u8  ┆ on  ┆ u8  ┆ --- ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆ --- ┆ u8  ┆     ┆ u8  ┆ Ver ┆ ce  ┆ fie ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ _nu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ --- ┆     ┆ u8  ┆     ┆ u8  ┆     ┆     ┆     ┆ u8  ┆ u8  ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆ ifi ┆ Ver ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆ i8  ┆ i8  ┆ ll  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ u8  ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ ifi ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ ed  ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 120 ┆ 36  ┆ 7.9 ┆ 0   ┆ 420 ┆ 715 ┆ 131 ┆ 255 ┆ 1   ┆ 1   ┆ 3   ┆ 27. ┆ 16  ┆ 2.0 ┆ 1.0 ┆ 4.0 ┆ 53. ┆ 1.0 ┆ 100 ┆ 0   ┆ 305 ┆ 6   ┆ 37. ┆ 711 ┆ 14  ┆ 155 ┆ 8   ┆ 190 ┆ 73. ┆ 0.0 ┆ 1.0 ┆ 2.0 ┆ 0   ┆ 0   ┆ 0.0 ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 0.0 ┆ 7   ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 258 ┆ 0   ┆ 201 ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ 00  ┆     ┆ 7   ┆     ┆ 00. ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆ 74  ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ .0  ┆     ┆ 02. ┆     ┆ 0   ┆ 7.0 ┆     ┆ 00. ┆     ┆ 45. ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 100 ┆ 36  ┆ 9.4 ┆ 3   ┆ 550 ┆ 695 ┆ 144 ┆ 73  ┆ 49  ┆ 10  ┆ 1   ┆ 18. ┆ 10  ┆ 4.0 ┆ 1.0 ┆ 0.0 ┆ 68. ┆ 1.0 ┆ 100 ┆ 2   ┆ 340 ┆ 2   ┆ 57. ┆ 684 ┆ 49  ┆ 105 ┆ 10  ┆ 209 ┆ 75. ┆ 0.0 ┆ 1.0 ┆ 1.0 ┆ 0   ┆ 0   ┆ 0.0 ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 0.0 ┆ 5   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 146 ┆ 0   ┆ 201 ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ 00  ┆     ┆ 4   ┆     ┆ 00. ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆ 79  ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ .0  ┆     ┆ 607 ┆     ┆ 5   ┆ 7.0 ┆     ┆ 00. ┆     ┆ 187 ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 800 ┆ 36  ┆ 16. ┆ 0   ┆ 120 ┆ 700 ┆ 137 ┆ 276 ┆ 34  ┆ 6   ┆ 3   ┆ 20. ┆ 34  ┆ 3.0 ┆ 2.0 ┆ 0.0 ┆ 88. ┆ 24. ┆ 97. ┆ 6   ┆ 388 ┆ 3   ┆ 92. ┆ 0.0 ┆ 152 ┆ 0.0 ┆ 6   ┆ 835 ┆ 85. ┆ 1.0 ┆ 1.0 ┆ 2.0 ┆ 0   ┆ 0   ┆ 0.0 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0.0 ┆ 19  ┆ 0   ┆ 1   ┆ 1   ┆ 0   ┆ 280 ┆ 0   ┆ 201 ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   │

## 8.3 Weight of Evidence (WoE)

In [18]:
from src.data.split import temporal_split, split_xy
from src.data.woe import WoEEncoder

# load cleaned data
df = pl.scan_parquet(INTERIM_DIR / "cleaned.parquet")

# temporal split
df_train, df_val, df_test = temporal_split(df, val_start="2018-08-01", test_start="2019-04-01")

# woe
woe      = WoEEncoder(min_samples=2)
df_train = woe.fit_transform(df_train)
df_val   = woe.transform(df_val)
df_test  = woe.transform(df_test)

# check iv summary before proceeding
print(woe.iv_summary())

# drop weak features across all splits
weak_cols = woe.drop_weak_features(threshold=0.02)
if weak_cols:
    print(f"dropping {len(weak_cols)} weak features: {weak_cols}")
    df_train = df_train.drop(weak_cols)
    df_val   = df_val.drop(weak_cols)
    df_test  = df_test.drop(weak_cols)

woe encoder saved to /home/adhitizki/Project/202607_credit-risk-personal/artifact/preprocessing/woe_encoder.pkl
               feature        iv predictive_power
0                grade  0.453791           strong
1  verification_status  0.053164             weak
2       home_ownership  0.034786             weak
3           addr_state  0.017355          useless
4              purpose  0.015975          useless
5     application_type  0.004744          useless
6  initial_list_status  0.000705          useless
dropping 4 weak features: ['initial_list_status_woe', 'application_type_woe', 'purpose_woe', 'addr_state_woe']

In [20]:
df_train.collect()

shape: (845_232, 51)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ loa ┆ ter ┆ int ┆ emp ┆ ann ┆ fic ┆ mo_ ┆ mo_ ┆ mo_ ┆ mo_ ┆ num ┆ dti ┆ tot ┆ ope ┆ ope ┆ ope ┆ all ┆ tot ┆ pct ┆ mor ┆ tot ┆ num ┆ rev ┆ max ┆ mth ┆ tot ┆ mth ┆ tot ┆ il_ ┆ inq ┆ inq ┆ inq ┆ del ┆ num ┆ num ┆ num ┆ col ┆ pub ┆ pub ┆ tot ┆ num ┆ mth ┆ mth ┆ mth ┆ emp ┆ cr_ ┆ def ┆ iss ┆ gra ┆ hom ┆ ver │
│ n_a ┆ m   ┆ _ra ┆ _le ┆ ual ┆ o_r ┆ sin ┆ sin ┆ sin ┆ sin ┆ _tl ┆ --- ┆ al_ ┆ n_a ┆ n_i ┆ n_r ┆ _ut ┆ al_ ┆ _tl ┆ t_a ┆ _cu ┆ _ac ┆ ol_ ┆ _ba ┆ s_s ┆ al_ ┆ s_s ┆ al_ ┆ uti ┆ _la ┆ _fi ┆ _la ┆ inq ┆ _ac ┆ _tl ┆ _tl ┆ lec ┆ _re ┆ _re ┆ _co ┆ _il ┆ s_s ┆ s_s ┆ s_s ┆ _le ┆ age ┆ aul ┆ ue_ ┆ de_ ┆ e_o ┆ ifi │
│ mnt ┆ --- ┆ te  ┆ ngt ┆ _in ┆ ang ┆ _ol ┆ _ol ┆ _rc ┆ _rc ┆ _op ┆ f64 ┆ acc ┆ ct_ ┆ l_1 ┆ v_2 ┆ il  ┆ cu_ ┆ _nv ┆ cc  ┆ r_b ┆ tv_ ┆ uti ┆ l_b ┆ inc ┆ bc_ ┆ inc ┆ bal ┆ l   ┆ st_ ┆ --- ┆ st_ ┆ _2y ┆ cts ┆ _12 ┆ _90 ┆ tio ┆ c   ┆ c_b ┆ ll_ ┆ _tl ┆ inc ┆ inc ┆ inc ┆ ngt ┆ _mt ┆ t   ┆ d   ┆ woe ┆ wne ┆ cat │
│ --- ┆ i64 ┆ --- ┆ h   ┆ c   ┆ e_l ┆ d_i ┆ d_r ┆ nt_ ┆ nt_ ┆ _pa ┆     ┆ --- ┆ il  ┆ 2m  ┆ 4m  ┆ --- ┆ tl  ┆ r_d ┆ --- ┆ al  ┆ rev ┆ l   ┆ c   ┆ e_r ┆ lim ┆ e_r ┆ _il ┆ --- ┆ 6mt ┆ f64 ┆ 12m ┆ rs  ┆ _ev ┆ 0dp ┆ g_d ┆ ns_ ┆ --- ┆ ank ┆ amt ┆ --- ┆ e_r ┆ e_l ┆ e_l ┆ h_n ┆ hs  ┆ --- ┆ --- ┆ --- ┆ rsh ┆ ion │
│ i64 ┆     ┆ f64 ┆ --- ┆ --- ┆ ow  ┆ l_a ┆ ev_ ┆ rev ┆ tl  ┆ st_ ┆     ┆ i64 ┆ --- ┆ --- ┆ --- ┆ f64 ┆ --- ┆ lq  ┆ i64 ┆ --- ┆ _tl ┆ --- ┆ --- ┆ ece ┆ it  ┆ cnt ┆ --- ┆ f64 ┆ hs  ┆     ┆ --- ┆ --- ┆ er_ ┆ d_2 ┆ pd_ ┆ 12_ ┆ i64 ┆ rup ┆ --- ┆ i64 ┆ ece ┆ ast ┆ ast ┆ ull ┆ --- ┆ i8  ┆ dat ┆ f64 ┆ ip_ ┆ _st │
│     ┆     ┆     ┆ i64 ┆ f64 ┆ --- ┆ cct ┆ tl_ ┆ _tl ┆ --- ┆ 12m ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆     ┆ f64 ┆ --- ┆     ┆ f64 ┆ --- ┆ f64 ┆ f64 ┆ nt_ ┆ --- ┆ _il ┆ f64 ┆     ┆ --- ┆     ┆ f64 ┆ i64 ┆ 120 ┆ m   ┆ 24m ┆ mth ┆     ┆ tci ┆ f64 ┆     ┆ nt_ ┆ _re ┆ _ma ┆ --- ┆ i64 ┆     ┆ eti ┆     ┆ woe ┆ atu │
│     ┆     ┆     ┆     ┆     ┆ i64 ┆ --- ┆ op  ┆ _op ┆ i64 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆ i64 ┆     ┆     ┆ bc  ┆ f64 ┆ --- ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆ _pd ┆ --- ┆ --- ┆ s_e ┆     ┆ es  ┆     ┆     ┆ inq ┆ cor ┆ jor ┆ i8  ┆     ┆     ┆ me[ ┆     ┆ --- ┆ s_w │
│     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ f64 ┆ i64 ┆ x_m ┆     ┆ --- ┆     ┆     ┆ _nu ┆ d_n ┆ _de ┆     ┆     ┆     ┆ ms] ┆     ┆ f64 ┆ oe  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆ ed  ┆     ┆ i64 ┆     ┆     ┆ ll  ┆ ull ┆ rog ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ _nu ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆ i8  ┆ i8  ┆ ll  ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 120 ┆ 36  ┆ 7.9 ┆ 0   ┆ 420 ┆ 715 ┆ 131 ┆ 255 ┆ 1   ┆ 1   ┆ 3   ┆ 27. ┆ 16  ┆ 2.0 ┆ 1.0 ┆ 4.0 ┆ 53. ┆ 1.0 ┆ 100 ┆ 0   ┆ 305 ┆ 6   ┆ 37. ┆ 711 ┆ 14  ┆ 155 ┆ 8   ┆ 190 ┆ 73. ┆ 0.0 ┆ 1.0 ┆ 2.0 ┆ 0   ┆ 0   ┆ 0.0 ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 0.0 ┆ 7   ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 258 ┆ 0   ┆ 201 ┆ -1. ┆ 0.0 ┆ 0.0 │
│ 00  ┆     ┆ 7   ┆     ┆ 00. ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆ 74  ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ .0  ┆     ┆ 02. ┆     ┆ 0   ┆ 7.0 ┆     ┆ 00. ┆     ┆ 45. ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7-0 ┆ 292 ┆ 113 ┆ 107 │
│     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 ┆ 049 ┆ 45  ┆ 47  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     │
│ 100 ┆ 36  ┆ 9.4 ┆ 3   ┆ 550 ┆ 695 ┆ 144 ┆ 73  ┆ 49  ┆ 10  ┆ 1   ┆ 18. ┆ 10  ┆ 4.0 ┆ 1.0 ┆ 0.0 ┆ 68. ┆ 1.0 ┆ 100 ┆ 2   ┆ 340 ┆ 2   ┆ 57. ┆ 684 ┆ 49  ┆ 105 ┆ 10  ┆ 209 ┆ 75. ┆ 0.0 ┆ 1.0 ┆ 1.0 ┆ 0   ┆ 0   ┆ 0.0 ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 0.0 ┆ 5   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 146 ┆ 0   ┆ 201 ┆ -0. ┆ -0. ┆ -0. │
│ 00  ┆     ┆ 4   ┆     ┆ 00. ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆ 79  ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ .0  ┆     ┆ 607 ┆     ┆ 5   ┆ 7.0 ┆     ┆ 00. ┆     ┆ 187 ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7-0 ┆ 425 ┆ 191 ┆ 308 │
│     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 ┆ 884 ┆ 622 ┆ 441 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     │
│ 800 ┆ 36  ┆ 16. ┆ 0   ┆ 120 ┆ 700 ┆ 137 ┆ 276 ┆ 34  ┆ 6   ┆ 3   ┆ 20. ┆ 34  ┆ 3.0 ┆ 2.0 ┆ 0.0 ┆ 88. ┆ 24. ┆ 97. ┆ 6   ┆ 388 ┆ 3   ┆ 92. ┆ 0.0 ┆ 152 ┆ 0.0 ┆ 6   ┆ 835 ┆ 85. ┆ 1.0 ┆ 1.0 ┆ 2.0 ┆ 0   ┆ 0   ┆ 0.0 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0.0 ┆ 19  ┆ 0   ┆ 1   ┆ 1   ┆ 0   ┆ 280 ┆ 0   ┆ 201 ┆ 0.2 ┆ -0. ┆ -0. │
│ 0   ┆     ┆ 02  ┆     ┆ 000 ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆ 36  ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆ 1   ┆     ┆ 595 ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆ 72. ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7-0 ┆ 020 ┆ 191 ┆ 308 │
│     ┆     ┆     ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 ┆ 2   ┆ 622 ┆ 441 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     │
│ 128 ┆ 36  ┆ 13. ┆ 5   ┆ 900 ┆ 660 ┆ 154 ┆ 345 ┆ 5   ┆ 5   ┆ 3   ┆ 22. ┆ 23  ┆ 3.0 ┆ 2.0 ┆ 3.0 ┆ 86. ┆ 1.0 ┆ 83. ┆ 0   ┆ 933 ┆ 6   ┆ 86. ┆ 377 ┆ 5   ┆ 147 ┆ 6   ┆ 807 ┆ 91. ┆ 2.0 ┆ 0.0 ┆ 2.0 ┆ 0   ┆ 0   ┆ 0.0 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0.0 ┆ 15  ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 350 ┆ 0   ┆ 201 ┆ 0.2 ┆ 0.2 ┆ -0. │
│ 00  ┆     ┆ 59  ┆     ┆ 00. ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆ 63  ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 0   ┆     ┆ 75. ┆     ┆ 0   ┆ 7.0 ┆     ┆ 50. ┆     ┆ 15. ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7-0 ┆ 020 ┆ 068 ┆ 308 │
│     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 ┆ 2   ┆ 79  ┆ 441 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     │
│ 150 ┆ 36  ┆ 13. ┆ 4   ┆ 180 ┆ 680 ┆ 132 ┆ 489 ┆ 16  ┆ 13  ┆ 0   ┆ 38. ┆ 50  ┆ 4.0 ┆ 0.0 ┆ 1.0 ┆ 68. ┆ 8.0 ┆ 100 ┆ 4   ┆ 682 ┆ 14  ┆ 66. ┆ 221 ┆ 16  ┆ 116 ┆ 13  ┆ 190 ┆ 79. ┆ 0.0 ┆ 2.0 ┆ 0.0 ┆ 0   ┆ 0   ┆ 0.0 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0.0 ┆ 17  ┆ 0   ┆ 1   ┆ 1   ┆ 0   ┆ 496 ┆ 0   ┆ 201 ┆ 0.2 ┆ -0. ┆ 0.0 │
│ 00  ┆     ┆ 59  ┆     ┆ 000 ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆ 07  ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ .0  ┆     ┆ 000 ┆     ┆ 6   ┆ 27. ┆     ┆ 700 ┆     ┆ 233 ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7-0 ┆ 020 ┆ 191 ┆ 107 │
│     ┆     ┆     ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆     ┆     ┆ 0   ┆     ┆ .0  ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 ┆ 2   ┆ 622 ┆ 47  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     │
│ 400 ┆ 60  ┆ 7.9 ┆ 0   ┆ 200 ┆ 760 ┆ 155 ┆ 157 ┆ 0   ┆ 0   ┆ 2   ┆ 14. ┆ 68  ┆ 9.0 ┆ 1.0 ┆ 1.0 ┆ 54. ┆ 8.0 ┆ 100 ┆ 6   ┆ 354 ┆ 6   ┆ 13. ┆ 234 ┆ 28  ┆ 484 ┆ 11  ┆ 344 ┆ 99. ┆ 0.0 ┆ 4.0 ┆ 7.0 ┆ 0   ┆ 0   ┆ 0.0 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0.0 ┆ 35  ┆ 0   ┆ 1   ┆ 1   ┆ 1   ┆ 159 ┆ 1   ┆ 201 ┆ -1. ┆ 0.0 ┆ 0.2 │
│ 00  ┆     ┆ 7   ┆     ┆ 000 ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆ 37  ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ .0  ┆     ┆ 714 ┆     ┆ 1   ┆ 3.0 ┆     ┆ 00. ┆     ┆ 236 ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7-0 ┆ 292 ┆ 113 ┆ 940 │
│     ┆     ┆     ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 ┆ 049 ┆ 45  ┆ 62  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     │
│ 180 ┆ 60  ┆ 16. ┆ 0   ┆ 125 ┆ 675 ┆ 132 ┆ 124 ┆ 5   ┆ 5   ┆ 4   ┆ 9.5 ┆ 31  ┆ 2.0 ┆ 0.0 ┆ 6.0 ┆ 63. ┆ 0.0 ┆ 54. ┆ 0   ┆ 579 ┆ 11  ┆ 34. ┆ 562 ┆ 5   ┆ 516 ┆ 30  ┆ 399 ┆ 100 ┆ 1.0 ┆ 0.0 ┆ 2.0 ┆ 2   ┆ 10  ┆ 0.0 ┆ 2   ┆ 0   ┆ 0   ┆ 0   ┆ 0.0 ┆ 18  ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 133 ┆ 0   ┆ 201 ┆ 0.2 ┆ 0.2 ┆ -0. │
│ 00  ┆     ┆ 02  ┆     ┆ 000 ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 8   ┆     ┆ 41. ┆     ┆ 9   ┆ 9.0 ┆     ┆ 00. ┆     ┆ 58. ┆ .0  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7-0 ┆ 020 ┆ 068 ┆ 308 │
│     ┆     ┆     ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 ┆ 2   ┆ 79  ┆ 441 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     │

## 8.4 Data Transformation for Model Ready

In [22]:
import polars as pl

from src.data.ohe import one_hot_encode
from src.data.woe import WoEEncoder
from src.data.scaling import FeatureScaler
from src.data.split import temporal_split, split_xy

In [36]:
def split_save_data(df_train, df_val, df_test, 
                    init_name,
                    scaling=False):

    # split X y
    X_train, y_train = split_xy(df_train)
    X_val, y_val = split_xy(df_val)
    X_test, y_test = split_xy(df_test)

    # scaling
    if scaling:
        scaler = FeatureScaler()

        X_train = scaler.fit_transform(X_train)
        X_val   = scaler.transform(X_val)
        X_test  = scaler.transform(X_test)

        init_name = f"{init_name}_scale"

    # make directory
    dir_name = PROCESSED_DIR / f"{init_name}"
    Path(dir_name).mkdir(parents=True, exist_ok=True)

    # save file
    X_train.sink_parquet(dir_name / "X_train.parquet")
    y_train.sink_parquet(dir_name / "y_train.parquet")
    X_val.sink_parquet(dir_name / "X_val.parquet")
    y_val.sink_parquet(dir_name / "y_val.parquet")
    X_test.sink_parquet(dir_name / "X_test.parquet")
    y_test.sink_parquet(dir_name / "y_test.parquet")

### 8.4.1 OHE

In [38]:
# load data
df = pl.scan_parquet(INTERIM_DIR / "cleaned.parquet")

# ohe
df = one_hot_encode(df)

# split
df_train, df_val, df_test = temporal_split(df, val_start="2018-08-01", test_start="2019-04-01")

# split Xy and save
split_save_data(df_train, df_val, df_test, "ohe")

### 8.4.2 WoE

In [40]:
# load data
df = pl.scan_parquet(INTERIM_DIR / "cleaned.parquet")

# split
df_train, df_val, df_test = temporal_split(df, val_start="2018-08-01", test_start="2019-04-01")

# woe
woe      = WoEEncoder(min_samples=2)
df_train = woe.fit_transform(df_train)  # fits on train target, transforms
df_val   = woe.transform(df_val)        # applies train woe maps
df_test  = woe.transform(df_test)       # applies train woe maps

# check iv summary before proceeding
print(woe.iv_summary())

# drop weak features across all splits
weak_cols = woe.drop_weak_features(threshold=0.02)
if weak_cols:
    print(f"dropping {len(weak_cols)} weak features: {weak_cols}")
    df_train = df_train.drop(weak_cols)
    df_val   = df_val.drop(weak_cols)
    df_test  = df_test.drop(weak_cols)

# split Xy and save
split_save_data(df_train, df_val, df_test, "woe")

woe encoder saved to /home/adhitizki/Project/202607_credit-risk-personal/artifact/preprocessing/woe_encoder.pkl
               feature        iv predictive_power
0                grade  0.453791           strong
1  verification_status  0.053164             weak
2       home_ownership  0.034786             weak
3           addr_state  0.017355          useless
4              purpose  0.015975          useless
5     application_type  0.004744          useless
6  initial_list_status  0.000705          useless
dropping 4 weak features: ['initial_list_status_woe', 'application_type_woe', 'purpose_woe', 'addr_state_woe']

### 8.4.3 OHE + Scaling

In [41]:
# load data
df = pl.scan_parquet(INTERIM_DIR / "cleaned.parquet")

# ohe
df = one_hot_encode(df)

# split
df_train, df_val, df_test = temporal_split(df, val_start="2018-08-01", test_start="2019-04-01")

# split Xy and save
split_save_data(df_train, df_val, df_test, "ohe", True)

scaler saved to /home/adhitizki/Project/202607_credit-risk-personal/artifact/preprocessing/scaler.pkl

### 8.4.4 WoE + Scaling

In [42]:
# load data
df = pl.scan_parquet(INTERIM_DIR / "cleaned.parquet")

# split
df_train, df_val, df_test = temporal_split(df, val_start="2018-08-01", test_start="2019-04-01")

# woe
woe      = WoEEncoder(min_samples=2)
df_train = woe.fit_transform(df_train)  # fits on train target, transforms
df_val   = woe.transform(df_val)        # applies train woe maps
df_test  = woe.transform(df_test)       # applies train woe maps

# check iv summary before proceeding
print(woe.iv_summary())

# drop weak features across all splits
weak_cols = woe.drop_weak_features(threshold=0.02)
if weak_cols:
    print(f"dropping {len(weak_cols)} weak features: {weak_cols}")
    df_train = df_train.drop(weak_cols)
    df_val   = df_val.drop(weak_cols)
    df_test  = df_test.drop(weak_cols)

# split Xy and save
split_save_data(df_train, df_val, df_test, "woe", True)

woe encoder saved to /home/adhitizki/Project/202607_credit-risk-personal/artifact/preprocessing/woe_encoder.pkl
               feature        iv predictive_power
0                grade  0.453791           strong
1  verification_status  0.053164             weak
2       home_ownership  0.034786             weak
3           addr_state  0.017355          useless
4              purpose  0.015975          useless
5     application_type  0.004744          useless
6  initial_list_status  0.000705          useless
dropping 4 weak features: ['initial_list_status_woe', 'application_type_woe', 'purpose_woe', 'addr_state_woe']
scaler saved to /home/adhitizki/Project/202607_credit-risk-personal/artifact/preprocessing/scaler.pkl